//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcessAreaDetailMst
    {
        public int Id { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public Nullable<decimal> AllottedArea { get; set; }
        public Nullable<decimal> ExcessArea { get; set; }
        public Nullable<decimal> TotalArea { get; set; }
        public Nullable<decimal> ExcessAreaAllotmentRate { get; set; }
        public Nullable<decimal> LocationCharge { get; set; }
        public Nullable<decimal> ExcessCharge { get; set; }
        public Nullable<decimal> TotalExcessPremium { get; set; }
        public Nullable<decimal> OneTimeLeaseRent { get; set; }
        public Nullable<decimal> TotalExcessAreaCost { get; set; }
        public Nullable<System.DateTime> ExcessAreaDate { get; set; }
        public Nullable<System.DateTime> ExcessAreaValidDate { get; set; }
        public Nullable<decimal> PenalInterest { get; set; }
        public Nullable<decimal> PenalAmount { get; set; }
        public Nullable<decimal> TotalPayableAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
