//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firm_Director_Master
    {
        public int Director_Id { get; set; }
        public Nullable<int> Rid { get; set; }
        public string Director_Name { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> Director_Share { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public Nullable<System.DateTime> Approved_Date { get; set; }
        public Nullable<int> Is_Active { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Application_Id { get; set; }
        public Nullable<int> OnlineRequestNo { get; set; }
        public string sha_type { get; set; }
    
        public virtual ApplicationDetail ApplicationDetail { get; set; }
    }
}
