//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PIMSEntitiesContext : DbContext
    {
        public PIMSEntitiesContext()
            : base("name=PIMSEntitiesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OnlineExtensionDetail> OnlineExtensionDetails { get; set; }
        public virtual DbSet<OnlineFirmDirectorMaster> OnlineFirmDirectorMasters { get; set; }
        public virtual DbSet<OnlineFirmRequestMaster> OnlineFirmRequestMasters { get; set; }
        public virtual DbSet<OnlineFunctionalDetail> OnlineFunctionalDetails { get; set; }
        public virtual DbSet<OnlineGPA> OnlineGPAs { get; set; }
        public virtual DbSet<OnlineMortgageDetail> OnlineMortgageDetails { get; set; }
        public virtual DbSet<OnlinePropertyCancellationDetail> OnlinePropertyCancellationDetails { get; set; }
        public virtual DbSet<OnlineRentPermissionDetail> OnlineRentPermissionDetails { get; set; }
        public virtual DbSet<OnlineTransferMutation> OnlineTransferMutations { get; set; }
        public virtual DbSet<AccountHeadMst> AccountHeadMsts { get; set; }
        public virtual DbSet<AccountSubHeadMst> AccountSubHeadMsts { get; set; }
        public virtual DbSet<AllotmentMaster> AllotmentMasters { get; set; }
        public virtual DbSet<ApplicationDetail> ApplicationDetails { get; set; }
        public virtual DbSet<ApplicationPaymentDetail> ApplicationPaymentDetails { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<BankMst> BankMsts { get; set; }
        public virtual DbSet<BlockMst> BlockMsts { get; set; }
        public virtual DbSet<BranchMst> BranchMsts { get; set; }
        public virtual DbSet<Building_Plan_Master> Building_Plan_Master { get; set; }
        public virtual DbSet<Building_Plan_Trans> Building_Plan_Trans { get; set; }
        public virtual DbSet<Challan_Master> Challan_Master { get; set; }
        public virtual DbSet<Challan_Trans> Challan_Trans { get; set; }
        public virtual DbSet<ChecklistMaster> ChecklistMasters { get; set; }
        public virtual DbSet<ChecklistTran> ChecklistTrans { get; set; }
        public virtual DbSet<ChecklistTypeMaster> ChecklistTypeMasters { get; set; }
        public virtual DbSet<CircleRateMst> CircleRateMsts { get; set; }
        public virtual DbSet<CitizenService_Master> CitizenService_Master { get; set; }
        public virtual DbSet<Common_Config> Common_Config { get; set; }
        public virtual DbSet<Completion_Details> Completion_Details { get; set; }
        public virtual DbSet<Customer_ServiceRequest> Customer_ServiceRequest { get; set; }
        public virtual DbSet<Customer_ServiceRequestCharges> Customer_ServiceRequestCharges { get; set; }
        public virtual DbSet<Customer_ServiceRequestDocument> Customer_ServiceRequestDocument { get; set; }
        public virtual DbSet<Customer_ServiceStatusTrans> Customer_ServiceStatusTrans { get; set; }
        public virtual DbSet<CustomerMst> CustomerMsts { get; set; }
        public virtual DbSet<DemandNoteDetail> DemandNoteDetails { get; set; }
        public virtual DbSet<DepartmentMst> DepartmentMsts { get; set; }
        public virtual DbSet<DepartmentSubMst> DepartmentSubMsts { get; set; }
        public virtual DbSet<Director_Request_Master> Director_Request_Master { get; set; }
        public virtual DbSet<Document_Mst> Document_Mst { get; set; }
        public virtual DbSet<EmployeeMst> EmployeeMsts { get; set; }
        public virtual DbSet<EpassMaster> EpassMasters { get; set; }
        public virtual DbSet<ExcessAreaDetailMst> ExcessAreaDetailMsts { get; set; }
        public virtual DbSet<Extension_Details> Extension_Details { get; set; }
        public virtual DbSet<Firm_Director_Master> Firm_Director_Master { get; set; }
        public virtual DbSet<Firm_Master> Firm_Master { get; set; }
        public virtual DbSet<Firm_Type_Master> Firm_Type_Master { get; set; }
        public virtual DbSet<FloorMst> FloorMsts { get; set; }
        public virtual DbSet<FunctionalDetail> FunctionalDetails { get; set; }
        public virtual DbSet<GPA> GPAs { get; set; }
        public virtual DbSet<GroupHousingProjectMst> GroupHousingProjectMsts { get; set; }
        public virtual DbSet<HEAD_MASTER> HEAD_MASTER { get; set; }
        public virtual DbSet<HEAD_SUB_MASTER> HEAD_SUB_MASTER { get; set; }
        public virtual DbSet<InstallmentDuesPayment> InstallmentDuesPayments { get; set; }
        public virtual DbSet<InstallmentDuesPaymentTran> InstallmentDuesPaymentTrans { get; set; }
        public virtual DbSet<InterestMst> InterestMsts { get; set; }
        public virtual DbSet<Interview_Details> Interview_Details { get; set; }
        public virtual DbSet<KYADetail> KYADetails { get; set; }
        public virtual DbSet<LeaseRentPayment> LeaseRentPayments { get; set; }
        public virtual DbSet<LeaseRentPaymentTran> LeaseRentPaymentTrans { get; set; }
        public virtual DbSet<Letter_History> Letter_History { get; set; }
        public virtual DbSet<Letter_Signing_Authority> Letter_Signing_Authority { get; set; }
        public virtual DbSet<LocationChargeDetailMst> LocationChargeDetailMsts { get; set; }
        public virtual DbSet<LocationMst> LocationMsts { get; set; }
        public virtual DbSet<Merge_Property_Master> Merge_Property_Master { get; set; }
        public virtual DbSet<Merge_Property_Trans> Merge_Property_Trans { get; set; }
        public virtual DbSet<MortgageDetail> MortgageDetails { get; set; }
        public virtual DbSet<NDCDetailMst> NDCDetailMsts { get; set; }
        public virtual DbSet<NICsingalwindowSystem> NICsingalwindowSystems { get; set; }
        public virtual DbSet<Nominee_Details> Nominee_Details { get; set; }
        public virtual DbSet<OccupationMst> OccupationMsts { get; set; }
        public virtual DbSet<online_Director_Master> online_Director_Master { get; set; }
        public virtual DbSet<OnlineApplicationDetail> OnlineApplicationDetails { get; set; }
        public virtual DbSet<OnlineApplicationDetails_trans> OnlineApplicationDetails_trans { get; set; }
        public virtual DbSet<OnlineApplicationProcessDetail> OnlineApplicationProcessDetails { get; set; }
        public virtual DbSet<OnlineAreawithRegisandProcfee> OnlineAreawithRegisandProcfees { get; set; }
        public virtual DbSet<OnlineCheckListMaster> OnlineCheckListMasters { get; set; }
        public virtual DbSet<OnlineCheckLisTran> OnlineCheckLisTrans { get; set; }
        public virtual DbSet<OnlineSchemeDraw> OnlineSchemeDraws { get; set; }
        public virtual DbSet<PaymentDetailMaster> PaymentDetailMasters { get; set; }
        public virtual DbSet<PaymentDetailTran> PaymentDetailTrans { get; set; }
        public virtual DbSet<PaymentDuesCalculatedMst> PaymentDuesCalculatedMsts { get; set; }
        public virtual DbSet<PaymentLeaseRentMaster> PaymentLeaseRentMasters { get; set; }
        public virtual DbSet<PaymentLeaseRentTran> PaymentLeaseRentTrans { get; set; }
        public virtual DbSet<PaymentModeMst> PaymentModeMsts { get; set; }
        public virtual DbSet<PaymentReceiptMst> PaymentReceiptMsts { get; set; }
        public virtual DbSet<PaymentReceiptTran> PaymentReceiptTrans { get; set; }
        public virtual DbSet<PaymentScheduleMaster> PaymentScheduleMasters { get; set; }
        public virtual DbSet<PaymentScheduleTran> PaymentScheduleTrans { get; set; }
        public virtual DbSet<PaymentSubTypeMst> PaymentSubTypeMsts { get; set; }
        public virtual DbSet<PaymentTypeMst> PaymentTypeMsts { get; set; }
        public virtual DbSet<PossessionDetail> PossessionDetails { get; set; }
        public virtual DbSet<PRE_FULL_PAYMENT_NDC> PRE_FULL_PAYMENT_NDC { get; set; }
        public virtual DbSet<Process_Master> Process_Master { get; set; }
        public virtual DbSet<Product_Master> Product_Master { get; set; }
        public virtual DbSet<Property_Cancellation_Details> Property_Cancellation_Details { get; set; }
        public virtual DbSet<Property_Ledger> Property_Ledger { get; set; }
        public virtual DbSet<PropertyCompensationMst> PropertyCompensationMsts { get; set; }
        public virtual DbSet<PropertyLocationChargesTran> PropertyLocationChargesTrans { get; set; }
        public virtual DbSet<PropertyRateMst> PropertyRateMsts { get; set; }
        public virtual DbSet<PropertyTransaction> PropertyTransactions { get; set; }
        public virtual DbSet<PropertyTypeMst> PropertyTypeMsts { get; set; }
        public virtual DbSet<QuotaMst> QuotaMsts { get; set; }
        public virtual DbSet<RebateMst> RebateMsts { get; set; }
        public virtual DbSet<RECEIPT_AMOUNT_TRANS> RECEIPT_AMOUNT_TRANS { get; set; }
        public virtual DbSet<RECEIPT_DETAIL_MASTER> RECEIPT_DETAIL_MASTER { get; set; }
        public virtual DbSet<RECEIPT_SUB_HEAD> RECEIPT_SUB_HEAD { get; set; }
        public virtual DbSet<RECIEPT_HEAD> RECIEPT_HEAD { get; set; }
        public virtual DbSet<RegistryDetail> RegistryDetails { get; set; }
        public virtual DbSet<ReligionMst> ReligionMsts { get; set; }
        public virtual DbSet<RentPermissionDetail> RentPermissionDetails { get; set; }
        public virtual DbSet<SchemeBankTran> SchemeBankTrans { get; set; }
        public virtual DbSet<SchemeCostTran> SchemeCostTrans { get; set; }
        public virtual DbSet<SchemeDepartmentTran> SchemeDepartmentTrans { get; set; }
        public virtual DbSet<SchemeMst> SchemeMsts { get; set; }
        public virtual DbSet<SchemeNotifTran> SchemeNotifTrans { get; set; }
        public virtual DbSet<SchemePropTran> SchemePropTrans { get; set; }
        public virtual DbSet<SchemeQuotaTran> SchemeQuotaTrans { get; set; }
        public virtual DbSet<SchemeRebateTran> SchemeRebateTrans { get; set; }
        public virtual DbSet<SchemeRefundTran> SchemeRefundTrans { get; set; }
        public virtual DbSet<SchemeTypeMst> SchemeTypeMsts { get; set; }
        public virtual DbSet<SectorMst> SectorMsts { get; set; }
        public virtual DbSet<ServiceCheckList_Master> ServiceCheckList_Master { get; set; }
        public virtual DbSet<ServiceRequest_Documents> ServiceRequest_Documents { get; set; }
        public virtual DbSet<SMSServicesMst> SMSServicesMsts { get; set; }
        public virtual DbSet<StatusMaster> StatusMasters { get; set; }
        public virtual DbSet<SubDepartmentMst> SubDepartmentMsts { get; set; }
        public virtual DbSet<Succ_Mut_Trans> Succ_Mut_Trans { get; set; }
        public virtual DbSet<TemplateMaster> TemplateMasters { get; set; }
        public virtual DbSet<Transfer_Type> Transfer_Type { get; set; }
        public virtual DbSet<UmApplicationMaster> UmApplicationMasters { get; set; }
        public virtual DbSet<UmDepartmentMaster> UmDepartmentMasters { get; set; }
        public virtual DbSet<UmMenuMaster> UmMenuMasters { get; set; }
        public virtual DbSet<UmRoleAppTran> UmRoleAppTrans { get; set; }
        public virtual DbSet<UmRoleMaster> UmRoleMasters { get; set; }
        public virtual DbSet<UmRoleMasterTran> UmRoleMasterTrans { get; set; }
        public virtual DbSet<UmUserDepartmentTran> UmUserDepartmentTrans { get; set; }
        public virtual DbSet<UmUserMaster> UmUserMasters { get; set; }
        public virtual DbSet<UmUserMasterRole> UmUserMasterRoles { get; set; }
        public virtual DbSet<UnsuccessfulApplicantListMaster> UnsuccessfulApplicantListMasters { get; set; }
        public virtual DbSet<ValidatedPropertyDetailMst> ValidatedPropertyDetailMsts { get; set; }
        public virtual DbSet<NiveshMitraEntr_Master> NiveshMitraEntr_Master { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceStatu> ServiceStatus { get; set; }
        public virtual DbSet<ServiceStatusTran> ServiceStatusTrans { get; set; }
        public virtual DbSet<ServiceTran> ServiceTrans { get; set; }
        public virtual DbSet<PRE_PROP_HIRE_PURCHASE> PRE_PROP_HIRE_PURCHASE { get; set; }
        public virtual DbSet<Project_report> Project_report { get; set; }
        public virtual DbSet<Report_Template_temp> Report_Template_temp { get; set; }
        public virtual DbSet<temp_cal> temp_cal { get; set; }
        public virtual DbSet<temp_housing> temp_housing { get; set; }
        public virtual DbSet<Village_Master> Village_Master { get; set; }
        public virtual DbSet<OnlineService> OnlineServices { get; set; }
        public virtual DbSet<ClientRequest> ClientRequests { get; set; }
        public virtual DbSet<NICServiceStatu> NICServiceStatus { get; set; }
        public virtual DbSet<ServiceRejectionDetail> ServiceRejectionDetails { get; set; }
        public virtual DbSet<NICServiceMst> NICServiceMsts { get; set; }
        public virtual DbSet<SchemeAreaMst> SchemeAreaMsts { get; set; }
    
        public virtual ObjectResult<string> Sp_NewSchemereturn(Nullable<int> onlineapplicationid, Nullable<int> schemeid)
        {
            var onlineapplicationidParameter = onlineapplicationid.HasValue ?
                new ObjectParameter("Onlineapplicationid", onlineapplicationid) :
                new ObjectParameter("Onlineapplicationid", typeof(int));
    
            var schemeidParameter = schemeid.HasValue ?
                new ObjectParameter("schemeid", schemeid) :
                new ObjectParameter("schemeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Sp_NewSchemereturn", onlineapplicationidParameter, schemeidParameter);
        }
    }
}
