//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDCDetailMst
    {
        public int Id { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Department { get; set; }
        public string Applicant { get; set; }
        public string ApplicantAddress { get; set; }
        public string Sector { get; set; }
        public string Block { get; set; }
        public string PlotNo { get; set; }
        public Nullable<decimal> InstallmentDuesAmount { get; set; }
        public string InstallmentDateInWord { get; set; }
        public string InstallmentStatus { get; set; }
        public Nullable<System.DateTime> InstallmentPaidUptoDate { get; set; }
        public Nullable<decimal> InterestDuesAmount { get; set; }
        public string InterestDateInWord { get; set; }
        public string InterestDueStatus { get; set; }
        public Nullable<decimal> LeaseRentAmount { get; set; }
        public string LeaseRentDateInWord { get; set; }
        public Nullable<System.DateTime> LeaseRentPaidUptoDate { get; set; }
        public string LeaseRentStatus { get; set; }
        public Nullable<bool> IsTotalInstallmentPaid { get; set; }
        public Nullable<bool> IsOneTimeLeasePaid { get; set; }
        public Nullable<System.DateTime> NDCDate { get; set; }
        public string LetterNo { get; set; }
        public string LetterDateInWord { get; set; }
        public string ChallanDetail { get; set; }
        public string ChallanAmount { get; set; }
        public string BankName { get; set; }
        public string ReferenceNo { get; set; }
        public string LetterType { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ValidatorId { get; set; }
        public Nullable<System.DateTime> ValidatedDate { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<bool> IsLetterIssued { get; set; }
        public Nullable<System.DateTime> NDCDispatchDate { get; set; }
        public string ChallanId { get; set; }
        public string Remarks { get; set; }
        public string NDCTemplate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ServiceRequestId { get; set; }
        public string Comment { get; set; }
    }
}
