//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReceiptTran
    {
        public long Id { get; set; }
        public Nullable<long> ReceiptRefId { get; set; }
        public Nullable<int> ReceiptHeadId { get; set; }
        public Nullable<int> ReceiptSubHeadId { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public Nullable<long> ChallanId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual PaymentReceiptMst PaymentReceiptMst { get; set; }
        public virtual RECEIPT_SUB_HEAD RECEIPT_SUB_HEAD { get; set; }
        public virtual RECIEPT_HEAD RECIEPT_HEAD { get; set; }
    }
}
