//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_report
    {
        public int rid { get; set; }
        public Nullable<int> departmentid { get; set; }
        public string LeaseDeedDate { get; set; }
        public string PossessionOrderDate { get; set; }
        public string PossessionDate { get; set; }
        public string FunctionalDate { get; set; }
        public string TransferDate { get; set; }
        public string MutationDate { get; set; }
        public string MortgageDate { get; set; }
        public string BankNameandBranch { get; set; }
        public string RentingDate { get; set; }
        public string TenantName { get; set; }
        public string TenantProject { get; set; }
        public string ExtenctionDate { get; set; }
        public string PRDDHIRE_AGREEMENT_DATE { get; set; }
        public string PRDDOLD_EXPIRY_DATE { get; set; }
        public string TotalPrimamPaid { get; set; }
        public string OTLRPaid { get; set; }
        public string NDCDate { get; set; }
        public string projectName { get; set; }
    }
}
