//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSServicesMst
    {
        public int Id { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public string MobileNo { get; set; }
        public string SMSType { get; set; }
        public string Heading { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
        public string SenderId { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
