//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NoidaPMSEntities : DbContext
    {
        public NoidaPMSEntities()
            : base("name=NoidaPMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OnlineExtensionDetail> OnlineExtensionDetails { get; set; }
        public virtual DbSet<OnlineFirmDirectorMaster> OnlineFirmDirectorMasters { get; set; }
        public virtual DbSet<OnlineFirmRequestMaster> OnlineFirmRequestMasters { get; set; }
        public virtual DbSet<OnlineFunctionalDetail> OnlineFunctionalDetails { get; set; }
        public virtual DbSet<OnlineGPA> OnlineGPAs { get; set; }
        public virtual DbSet<OnlineMortgageDetail> OnlineMortgageDetails { get; set; }
        public virtual DbSet<OnlinePropertyCancellationDetail> OnlinePropertyCancellationDetails { get; set; }
        public virtual DbSet<OnlineRentPermissionDetail> OnlineRentPermissionDetails { get; set; }
        public virtual DbSet<OnlineTransferMutation> OnlineTransferMutations { get; set; }
        public virtual DbSet<AccountHeadMst> AccountHeadMsts { get; set; }
        public virtual DbSet<AccountSubHeadMst> AccountSubHeadMsts { get; set; }
        public virtual DbSet<AlloteeListMaster> AlloteeListMasters { get; set; }
        public virtual DbSet<ApplicationDetail> ApplicationDetails { get; set; }
        public virtual DbSet<ApplicationPaymentDetail> ApplicationPaymentDetails { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<Auto_Schedule> Auto_Schedule { get; set; }
        public virtual DbSet<BankMst> BankMsts { get; set; }
        public virtual DbSet<BlockMst> BlockMsts { get; set; }
        public virtual DbSet<Building_Plan_Master> Building_Plan_Master { get; set; }
        public virtual DbSet<Building_Plan_Trans> Building_Plan_Trans { get; set; }
        public virtual DbSet<Challan_Trans> Challan_Trans { get; set; }
        public virtual DbSet<ChecklistMaster> ChecklistMasters { get; set; }
        public virtual DbSet<ChecklistTran> ChecklistTrans { get; set; }
        public virtual DbSet<ChecklistTypeMaster> ChecklistTypeMasters { get; set; }
        public virtual DbSet<CircleRateMst> CircleRateMsts { get; set; }
        public virtual DbSet<Common_Config> Common_Config { get; set; }
        public virtual DbSet<Completion_Details> Completion_Details { get; set; }
        public virtual DbSet<DepartmentMst> DepartmentMsts { get; set; }
        public virtual DbSet<Document_Mst> Document_Mst { get; set; }
        public virtual DbSet<Firm_Type_Master> Firm_Type_Master { get; set; }
        public virtual DbSet<FloorMst> FloorMsts { get; set; }
        public virtual DbSet<FunctionalDetail> FunctionalDetails { get; set; }
        public virtual DbSet<GPA> GPAs { get; set; }
        public virtual DbSet<GroupHousingProjectMst> GroupHousingProjectMsts { get; set; }
        public virtual DbSet<HEAD_MASTER> HEAD_MASTER { get; set; }
        public virtual DbSet<HEAD_SUB_MASTER> HEAD_SUB_MASTER { get; set; }
        public virtual DbSet<InterestMst> InterestMsts { get; set; }
        public virtual DbSet<Interview_Details> Interview_Details { get; set; }
        public virtual DbSet<Letter_History_new> Letter_History_new { get; set; }
        public virtual DbSet<Letter_Signing_Authority> Letter_Signing_Authority { get; set; }
        public virtual DbSet<MediaTypeMst> MediaTypeMsts { get; set; }
        public virtual DbSet<Merge_Property_Master> Merge_Property_Master { get; set; }
        public virtual DbSet<Merge_Property_Trans> Merge_Property_Trans { get; set; }
        public virtual DbSet<MortgageDetail> MortgageDetails { get; set; }
        public virtual DbSet<NICsingalwindowSystem> NICsingalwindowSystems { get; set; }
        public virtual DbSet<NOC_MASTER> NOC_MASTER { get; set; }
        public virtual DbSet<Nominee_Details> Nominee_Details { get; set; }
        public virtual DbSet<NotificationMediaTran> NotificationMediaTrans { get; set; }
        public virtual DbSet<NotificationPaymentModeTran> NotificationPaymentModeTrans { get; set; }
        public virtual DbSet<Noting_File_Master> Noting_File_Master { get; set; }
        public virtual DbSet<Noting_File_Trans> Noting_File_Trans { get; set; }
        public virtual DbSet<OccupationMst> OccupationMsts { get; set; }
        public virtual DbSet<online_Director_Master> online_Director_Master { get; set; }
        public virtual DbSet<OnlineApplicationDetail> OnlineApplicationDetails { get; set; }
        public virtual DbSet<OnlineApplicationDetails_trans> OnlineApplicationDetails_trans { get; set; }
        public virtual DbSet<OnlineApplicationProcessDetail> OnlineApplicationProcessDetails { get; set; }
        public virtual DbSet<OnlineAreawithRegisandProcfee> OnlineAreawithRegisandProcfees { get; set; }
        public virtual DbSet<OnlineCheckLisTran> OnlineCheckLisTrans { get; set; }
        public virtual DbSet<OnlineSchemeDraw> OnlineSchemeDraws { get; set; }
        public virtual DbSet<PaymentDetailMaster> PaymentDetailMasters { get; set; }
        public virtual DbSet<PaymentDetailTran> PaymentDetailTrans { get; set; }
        public virtual DbSet<PaymentLeaseRentMaster> PaymentLeaseRentMasters { get; set; }
        public virtual DbSet<PaymentLeaseRentTran> PaymentLeaseRentTrans { get; set; }
        public virtual DbSet<PaymentModeMst> PaymentModeMsts { get; set; }
        public virtual DbSet<PaymentScheduleMaster> PaymentScheduleMasters { get; set; }
        public virtual DbSet<PaymentSubTypeMst> PaymentSubTypeMsts { get; set; }
        public virtual DbSet<PaymentTypeMst> PaymentTypeMsts { get; set; }
        public virtual DbSet<PRE_FULL_PAYMENT_NDC_NEW> PRE_FULL_PAYMENT_NDC_NEW { get; set; }
        public virtual DbSet<Process_Master> Process_Master { get; set; }
        public virtual DbSet<Product_Master> Product_Master { get; set; }
        public virtual DbSet<Property_Cancellation_Details> Property_Cancellation_Details { get; set; }
        public virtual DbSet<Property_Ledger> Property_Ledger { get; set; }
        public virtual DbSet<PropertyLocationChargesTran> PropertyLocationChargesTrans { get; set; }
        public virtual DbSet<PropertyTransaction> PropertyTransactions { get; set; }
        public virtual DbSet<PropertyTypeMst> PropertyTypeMsts { get; set; }
        public virtual DbSet<QuotaMst> QuotaMsts { get; set; }
        public virtual DbSet<RebateMst> RebateMsts { get; set; }
        public virtual DbSet<RECEIPT_SUB_HEAD> RECEIPT_SUB_HEAD { get; set; }
        public virtual DbSet<RECIEPT_HEAD> RECIEPT_HEAD { get; set; }
        public virtual DbSet<ReligionMst> ReligionMsts { get; set; }
        public virtual DbSet<RentPermissionDetail> RentPermissionDetails { get; set; }
        public virtual DbSet<SchemeBankTran> SchemeBankTrans { get; set; }
        public virtual DbSet<SchemeDepartmentTran> SchemeDepartmentTrans { get; set; }
        public virtual DbSet<SchemeNotifTran> SchemeNotifTrans { get; set; }
        public virtual DbSet<SchemeQuotaTran> SchemeQuotaTrans { get; set; }
        public virtual DbSet<SchemeRebateTran> SchemeRebateTrans { get; set; }
        public virtual DbSet<SchemeRefundTran> SchemeRefundTrans { get; set; }
        public virtual DbSet<SchemeTypeMst> SchemeTypeMsts { get; set; }
        public virtual DbSet<SectorMst> SectorMsts { get; set; }
        public virtual DbSet<ServiceCheckList_Master> ServiceCheckList_Master { get; set; }
        public virtual DbSet<ServiceRequest_Documents> ServiceRequest_Documents { get; set; }
        public virtual DbSet<SigningOfficerMaster> SigningOfficerMasters { get; set; }
        public virtual DbSet<StampDutyMaster> StampDutyMasters { get; set; }
        public virtual DbSet<StatusMaster> StatusMasters { get; set; }
        public virtual DbSet<SubDepartmentMst> SubDepartmentMsts { get; set; }
        public virtual DbSet<Succ_Mut_Trans> Succ_Mut_Trans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TemplateMaster> TemplateMasters { get; set; }
        public virtual DbSet<Transfer_Type> Transfer_Type { get; set; }
        public virtual DbSet<UmApplicationMaster> UmApplicationMasters { get; set; }
        public virtual DbSet<UmDepartmentMaster> UmDepartmentMasters { get; set; }
        public virtual DbSet<UmMenuMaster> UmMenuMasters { get; set; }
        public virtual DbSet<UmRoleAppTran> UmRoleAppTrans { get; set; }
        public virtual DbSet<UmRoleMasterTran> UmRoleMasterTrans { get; set; }
        public virtual DbSet<UmUserDepartmentTran> UmUserDepartmentTrans { get; set; }
        public virtual DbSet<UmUserMasterRole> UmUserMasterRoles { get; set; }
        public virtual DbSet<UnsuccessfulApplicantListMaster> UnsuccessfulApplicantListMasters { get; set; }
        public virtual DbSet<LeaseRentPayment_Old> LeaseRentPayment_Old { get; set; }
        public virtual DbSet<PRE_PROP_HIRE_PURCHASE> PRE_PROP_HIRE_PURCHASE { get; set; }
        public virtual DbSet<Project_report> Project_report { get; set; }
        public virtual DbSet<Report_Template_temp> Report_Template_temp { get; set; }
        public virtual DbSet<Village_Master> Village_Master { get; set; }
        public virtual DbSet<VecantPropertyList> VecantPropertyLists { get; set; }
        public virtual DbSet<view_approval_pending_request> view_approval_pending_request { get; set; }
        public virtual DbSet<View_Service_report> View_Service_report { get; set; }
        public virtual DbSet<View_Transfer_Charges_Check> View_Transfer_Charges_Check { get; set; }
        public virtual DbSet<ViewAllotmentMoneyCheck> ViewAllotmentMoneyChecks { get; set; }
        public virtual DbSet<ViewAllUserApplicationRoleDetail> ViewAllUserApplicationRoleDetails { get; set; }
        public virtual DbSet<ViewApplicationMenuMaster> ViewApplicationMenuMasters { get; set; }
        public virtual DbSet<ViewLeaseRentCheck> ViewLeaseRentChecks { get; set; }
        public virtual DbSet<ViewLeaseRentPayment> ViewLeaseRentPayments { get; set; }
        public virtual DbSet<ViewRoleWiseApplication> ViewRoleWiseApplications { get; set; }
        public virtual DbSet<ViewUmUserMaster> ViewUmUserMasters { get; set; }
        public virtual DbSet<Director_Request_Master> Director_Request_Master { get; set; }
        public virtual DbSet<Extension_Details> Extension_Details { get; set; }
        public virtual DbSet<RegistryDetail> RegistryDetails { get; set; }
        public virtual DbSet<AllotmentMaster> AllotmentMasters { get; set; }
        public virtual DbSet<Firm_Master> Firm_Master { get; set; }
        public virtual DbSet<SchemeCostTran> SchemeCostTrans { get; set; }
        public virtual DbSet<PossessionDetail> PossessionDetails { get; set; }
        public virtual DbSet<ViewReceiptMaster> ViewReceiptMasters { get; set; }
        public virtual DbSet<UmUserMaster> UmUserMasters { get; set; }
        public virtual DbSet<temp_cal> temp_cal { get; set; }
        public virtual DbSet<Firm_Director_Master> Firm_Director_Master { get; set; }
        public virtual DbSet<InstallmentDuesPaymentTran> InstallmentDuesPaymentTrans { get; set; }
        public virtual DbSet<LeaseRentPaymentTran> LeaseRentPaymentTrans { get; set; }
        public virtual DbSet<UmRoleMaster> UmRoleMasters { get; set; }
        public virtual DbSet<PRE_FULL_PAYMENT_NDC> PRE_FULL_PAYMENT_NDC { get; set; }
        public virtual DbSet<InstallmentDuesPayment> InstallmentDuesPayments { get; set; }
        public virtual DbSet<BranchMst> BranchMsts { get; set; }
        public virtual DbSet<RECEIPT_DETAIL_MASTER> RECEIPT_DETAIL_MASTER { get; set; }
        public virtual DbSet<RECEIPTBEFORE2009> RECEIPTBEFORE2009 { get; set; }
        public virtual DbSet<SchemeMst> SchemeMsts { get; set; }
        public virtual DbSet<OnlineCheckListMaster> OnlineCheckListMasters { get; set; }
        public virtual DbSet<ViewAllPropertyDetail> ViewAllPropertyDetails { get; set; }
        public virtual DbSet<PaymentScheduleTran> PaymentScheduleTrans { get; set; }
        public virtual DbSet<PaymentReceiptMst> PaymentReceiptMsts { get; set; }
        public virtual DbSet<PaymentReceiptTran> PaymentReceiptTrans { get; set; }
        public virtual DbSet<CustomerMst> CustomerMsts { get; set; }
        public virtual DbSet<KYADetail> KYADetails { get; set; }
        public virtual DbSet<LocationMst> LocationMsts { get; set; }
        public virtual DbSet<SchemePropTran> SchemePropTrans { get; set; }
        public virtual DbSet<LocationChargeDetailMst> LocationChargeDetailMsts { get; set; }
        public virtual DbSet<ExcessAreaDetailMst> ExcessAreaDetailMsts { get; set; }
        public virtual DbSet<NiveshMitraEntr_Master> NiveshMitraEntr_Master { get; set; }
        public virtual DbSet<CitizenService_Master> CitizenService_Master { get; set; }
        public virtual DbSet<PropertyCompensationMst> PropertyCompensationMsts { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceStatu> ServiceStatus { get; set; }
        public virtual DbSet<ServiceStatusTran> ServiceStatusTrans { get; set; }
        public virtual DbSet<ServiceTran> ServiceTrans { get; set; }
        public virtual DbSet<viewInstutionalPBalance> viewInstutionalPBalances { get; set; }
        public virtual DbSet<PaymentDuesCalculatedMst> PaymentDuesCalculatedMsts { get; set; }
        public virtual DbSet<SMSServicesMst> SMSServicesMsts { get; set; }
        public virtual DbSet<DemandNoteDetail> DemandNoteDetails { get; set; }
        public virtual DbSet<NDCDetailMst> NDCDetailMsts { get; set; }
        public virtual DbSet<ValidatedPropertyDetailMst> ValidatedPropertyDetailMsts { get; set; }
        public virtual DbSet<PropertyRateMst> PropertyRateMsts { get; set; }
        public virtual DbSet<DepartmentSubMst> DepartmentSubMsts { get; set; }
        public virtual DbSet<Customer_ServiceStatusTrans> Customer_ServiceStatusTrans { get; set; }
        public virtual DbSet<Customer_ServiceRequest> Customer_ServiceRequest { get; set; }
        public virtual DbSet<LeaseRentPayment> LeaseRentPayments { get; set; }
        public virtual DbSet<UmUserSubDepartmentTran> UmUserSubDepartmentTrans { get; set; }
        public virtual DbSet<Customer_ServiceRequestCharges> Customer_ServiceRequestCharges { get; set; }
        public virtual DbSet<Customer_ServiceRequestDocument> Customer_ServiceRequestDocument { get; set; }
        public virtual DbSet<AllDefaulterList> AllDefaulterLists { get; set; }
        public virtual DbSet<EmployeeMst> EmployeeMsts { get; set; }
        public virtual DbSet<Challan_Master> Challan_Master { get; set; }
        public virtual DbSet<EpassMaster> EpassMasters { get; set; }
        public virtual DbSet<Letter_History> Letter_History { get; set; }
        public virtual DbSet<RECEIPT_AMOUNT_TRANS> RECEIPT_AMOUNT_TRANS { get; set; }
    
        public virtual ObjectResult<usp_GetServiceCIC_Result> usp_GetServiceCIC(Nullable<int> serviceReqid)
        {
            var serviceReqidParameter = serviceReqid.HasValue ?
                new ObjectParameter("ServiceReqid", serviceReqid) :
                new ObjectParameter("ServiceReqid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetServiceCIC_Result>("usp_GetServiceCIC", serviceReqidParameter);
        }
    
        public virtual ObjectResult<usp_GetServiceExtensionFunction_Result> usp_GetServiceExtensionFunction(Nullable<int> serviceReqid)
        {
            var serviceReqidParameter = serviceReqid.HasValue ?
                new ObjectParameter("ServiceReqid", serviceReqid) :
                new ObjectParameter("ServiceReqid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetServiceExtensionFunction_Result>("usp_GetServiceExtensionFunction", serviceReqidParameter);
        }
    
        public virtual ObjectResult<usp_GetServiceGPA_Result> usp_GetServiceGPA(Nullable<int> serviceReqid)
        {
            var serviceReqidParameter = serviceReqid.HasValue ?
                new ObjectParameter("ServiceReqid", serviceReqid) :
                new ObjectParameter("ServiceReqid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetServiceGPA_Result>("usp_GetServiceGPA", serviceReqidParameter);
        }
    
        public virtual ObjectResult<usp_GetServiceMortgage_Result> usp_GetServiceMortgage(Nullable<int> serviceReqid)
        {
            var serviceReqidParameter = serviceReqid.HasValue ?
                new ObjectParameter("ServiceReqid", serviceReqid) :
                new ObjectParameter("ServiceReqid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetServiceMortgage_Result>("usp_GetServiceMortgage", serviceReqidParameter);
        }
    
        public virtual ObjectResult<usp_GetServiceMutation_Result> usp_GetServiceMutation(Nullable<int> serviceReqid)
        {
            var serviceReqidParameter = serviceReqid.HasValue ?
                new ObjectParameter("ServiceReqid", serviceReqid) :
                new ObjectParameter("ServiceReqid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetServiceMutation_Result>("usp_GetServiceMutation", serviceReqidParameter);
        }
    
        public virtual ObjectResult<usp_GetServiceRent_Result> usp_GetServiceRent(Nullable<int> serviceReqid)
        {
            var serviceReqidParameter = serviceReqid.HasValue ?
                new ObjectParameter("ServiceReqid", serviceReqid) :
                new ObjectParameter("ServiceReqid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetServiceRent_Result>("usp_GetServiceRent", serviceReqidParameter);
        }
    
        public virtual ObjectResult<usp_GetServiceRequestDetails_Result> usp_GetServiceRequestDetails(Nullable<int> serviceReqid)
        {
            var serviceReqidParameter = serviceReqid.HasValue ?
                new ObjectParameter("ServiceReqid", serviceReqid) :
                new ObjectParameter("ServiceReqid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetServiceRequestDetails_Result>("usp_GetServiceRequestDetails", serviceReqidParameter);
        }
    
        public virtual ObjectResult<usp_GetServiceTransfer_Result> usp_GetServiceTransfer(Nullable<int> serviceReqid)
        {
            var serviceReqidParameter = serviceReqid.HasValue ?
                new ObjectParameter("ServiceReqid", serviceReqid) :
                new ObjectParameter("ServiceReqid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetServiceTransfer_Result>("usp_GetServiceTransfer", serviceReqidParameter);
        }
    
        public virtual ObjectResult<Sp_AccountReport_list_Result> Sp_AccountReport_list(string fY, Nullable<int> departmentId)
        {
            var fYParameter = fY != null ?
                new ObjectParameter("fY", fY) :
                new ObjectParameter("fY", typeof(string));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("departmentId", departmentId) :
                new ObjectParameter("departmentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_AccountReport_list_Result>("Sp_AccountReport_list", fYParameter, departmentIdParameter);
        }
    
        public virtual ObjectResult<Sp_AccountReport_Receipt_list_Result> Sp_AccountReport_Receipt_list(string fY, Nullable<int> departmentId, string headiD)
        {
            var fYParameter = fY != null ?
                new ObjectParameter("fY", fY) :
                new ObjectParameter("fY", typeof(string));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("departmentId", departmentId) :
                new ObjectParameter("departmentId", typeof(int));
    
            var headiDParameter = headiD != null ?
                new ObjectParameter("headiD", headiD) :
                new ObjectParameter("headiD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_AccountReport_Receipt_list_Result>("Sp_AccountReport_Receipt_list", fYParameter, departmentIdParameter, headiDParameter);
        }
    
        public virtual ObjectResult<Sp_PaymentDemand_Result> Sp_PaymentDemand(Nullable<int> type, Nullable<int> departmentId, Nullable<int> sector, Nullable<int> block)
        {
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("departmentId", departmentId) :
                new ObjectParameter("departmentId", typeof(int));
    
            var sectorParameter = sector.HasValue ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(int));
    
            var blockParameter = block.HasValue ?
                new ObjectParameter("block", block) :
                new ObjectParameter("block", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_PaymentDemand_Result>("Sp_PaymentDemand", typeParameter, departmentIdParameter, sectorParameter, blockParameter);
        }
    
        public virtual ObjectResult<Sp_PaymentDemand_test_Result> Sp_PaymentDemand_test(Nullable<int> type, Nullable<int> departmentId, Nullable<int> sector, Nullable<int> block)
        {
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("departmentId", departmentId) :
                new ObjectParameter("departmentId", typeof(int));
    
            var sectorParameter = sector.HasValue ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(int));
    
            var blockParameter = block.HasValue ?
                new ObjectParameter("block", block) :
                new ObjectParameter("block", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_PaymentDemand_test_Result>("Sp_PaymentDemand_test", typeParameter, departmentIdParameter, sectorParameter, blockParameter);
        }
    
        public virtual ObjectResult<SpAccountLedger_Result> SpAccountLedger(Nullable<int> rid)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("Rid", rid) :
                new ObjectParameter("Rid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpAccountLedger_Result>("SpAccountLedger", ridParameter);
        }
    
        public virtual ObjectResult<SpAllotteeList_Result> SpAllotteeList(Nullable<int> schemeId, Nullable<int> departmentId, Nullable<System.DateTime> allotmentdate)
        {
            var schemeIdParameter = schemeId.HasValue ?
                new ObjectParameter("schemeId", schemeId) :
                new ObjectParameter("schemeId", typeof(int));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("departmentId", departmentId) :
                new ObjectParameter("departmentId", typeof(int));
    
            var allotmentdateParameter = allotmentdate.HasValue ?
                new ObjectParameter("allotmentdate", allotmentdate) :
                new ObjectParameter("allotmentdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpAllotteeList_Result>("SpAllotteeList", schemeIdParameter, departmentIdParameter, allotmentdateParameter);
        }
    
        public virtual ObjectResult<SpAllotteeListPaymentSchedule_Result> SpAllotteeListPaymentSchedule(Nullable<int> schemeId, Nullable<int> departmentId)
        {
            var schemeIdParameter = schemeId.HasValue ?
                new ObjectParameter("schemeId", schemeId) :
                new ObjectParameter("schemeId", typeof(int));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("departmentId", departmentId) :
                new ObjectParameter("departmentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpAllotteeListPaymentSchedule_Result>("SpAllotteeListPaymentSchedule", schemeIdParameter, departmentIdParameter);
        }
    
        public virtual int Sp_LatterPrintTemp(string registrationId, Nullable<int> templateId, Nullable<int> departmentId, string userId, Nullable<System.DateTime> letterDate, ObjectParameter commaString)
        {
            var registrationIdParameter = registrationId != null ?
                new ObjectParameter("registrationId", registrationId) :
                new ObjectParameter("registrationId", typeof(string));
    
            var templateIdParameter = templateId.HasValue ?
                new ObjectParameter("templateId", templateId) :
                new ObjectParameter("templateId", typeof(int));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("departmentId", departmentId) :
                new ObjectParameter("departmentId", typeof(int));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            var letterDateParameter = letterDate.HasValue ?
                new ObjectParameter("letterDate", letterDate) :
                new ObjectParameter("letterDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_LatterPrintTemp", registrationIdParameter, templateIdParameter, departmentIdParameter, userIdParameter, letterDateParameter, commaString);
        }
    
        public virtual int Sp_NewPaymentSchedule_OutSide(Nullable<int> rid, Nullable<decimal> principalAmount, Nullable<int> noOfInstallments, Nullable<int> frequencyOfInstallment, Nullable<System.DateTime> instalmentStartDate, Nullable<decimal> normalInterest, Nullable<decimal> penalInterest)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var principalAmountParameter = principalAmount.HasValue ?
                new ObjectParameter("PrincipalAmount", principalAmount) :
                new ObjectParameter("PrincipalAmount", typeof(decimal));
    
            var noOfInstallmentsParameter = noOfInstallments.HasValue ?
                new ObjectParameter("noOfInstallments", noOfInstallments) :
                new ObjectParameter("noOfInstallments", typeof(int));
    
            var frequencyOfInstallmentParameter = frequencyOfInstallment.HasValue ?
                new ObjectParameter("FrequencyOfInstallment", frequencyOfInstallment) :
                new ObjectParameter("FrequencyOfInstallment", typeof(int));
    
            var instalmentStartDateParameter = instalmentStartDate.HasValue ?
                new ObjectParameter("instalmentStartDate", instalmentStartDate) :
                new ObjectParameter("instalmentStartDate", typeof(System.DateTime));
    
            var normalInterestParameter = normalInterest.HasValue ?
                new ObjectParameter("NormalInterest", normalInterest) :
                new ObjectParameter("NormalInterest", typeof(decimal));
    
            var penalInterestParameter = penalInterest.HasValue ?
                new ObjectParameter("PenalInterest", penalInterest) :
                new ObjectParameter("PenalInterest", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_NewPaymentSchedule_OutSide", ridParameter, principalAmountParameter, noOfInstallmentsParameter, frequencyOfInstallmentParameter, instalmentStartDateParameter, normalInterestParameter, penalInterestParameter);
        }
    
        public virtual int Sp_PaymentReSchedule(Nullable<int> rid, Nullable<decimal> principle)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var principleParameter = principle.HasValue ?
                new ObjectParameter("Principle", principle) :
                new ObjectParameter("Principle", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_PaymentReSchedule", ridParameter, principleParameter);
        }
    
        public virtual int Sp_PropertyBank(string list, Nullable<int> scheme, Nullable<int> department, Nullable<int> sector, Nullable<int> block, Nullable<int> propertType, Nullable<int> floorArea, string registry)
        {
            var listParameter = list != null ?
                new ObjectParameter("list", list) :
                new ObjectParameter("list", typeof(string));
    
            var schemeParameter = scheme.HasValue ?
                new ObjectParameter("Scheme", scheme) :
                new ObjectParameter("Scheme", typeof(int));
    
            var departmentParameter = department.HasValue ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(int));
    
            var sectorParameter = sector.HasValue ?
                new ObjectParameter("Sector", sector) :
                new ObjectParameter("Sector", typeof(int));
    
            var blockParameter = block.HasValue ?
                new ObjectParameter("block", block) :
                new ObjectParameter("block", typeof(int));
    
            var propertTypeParameter = propertType.HasValue ?
                new ObjectParameter("PropertType", propertType) :
                new ObjectParameter("PropertType", typeof(int));
    
            var floorAreaParameter = floorArea.HasValue ?
                new ObjectParameter("floorArea", floorArea) :
                new ObjectParameter("floorArea", typeof(int));
    
            var registryParameter = registry != null ?
                new ObjectParameter("Registry", registry) :
                new ObjectParameter("Registry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_PropertyBank", listParameter, schemeParameter, departmentParameter, sectorParameter, blockParameter, propertTypeParameter, floorAreaParameter, registryParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_getServiceCheck(Nullable<int> rid, Nullable<int> templateId)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("Rid", rid) :
                new ObjectParameter("Rid", typeof(int));
    
            var templateIdParameter = templateId.HasValue ?
                new ObjectParameter("TemplateId", templateId) :
                new ObjectParameter("TemplateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_getServiceCheck", ridParameter, templateIdParameter);
        }
    
        public virtual ObjectResult<string> usp_getCitizenGraph(Nullable<int> reqType, Nullable<int> userdep)
        {
            var reqTypeParameter = reqType.HasValue ?
                new ObjectParameter("reqType", reqType) :
                new ObjectParameter("reqType", typeof(int));
    
            var userdepParameter = userdep.HasValue ?
                new ObjectParameter("userdep", userdep) :
                new ObjectParameter("userdep", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_getCitizenGraph", reqTypeParameter, userdepParameter);
        }
    
        public virtual ObjectResult<string> usp_GetServiceRequestMatrix(Nullable<int> ndepId, Nullable<int> nservId, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var ndepIdParameter = ndepId.HasValue ?
                new ObjectParameter("ndepId", ndepId) :
                new ObjectParameter("ndepId", typeof(int));
    
            var nservIdParameter = nservId.HasValue ?
                new ObjectParameter("nservId", nservId) :
                new ObjectParameter("nservId", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_GetServiceRequestMatrix", ndepIdParameter, nservIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_DuesCalculationTillDate(string rID, Nullable<System.DateTime> c, Nullable<int> landusetype)
        {
            var rIDParameter = rID != null ?
                new ObjectParameter("RID", rID) :
                new ObjectParameter("RID", typeof(string));
    
            var cParameter = c.HasValue ?
                new ObjectParameter("c", c) :
                new ObjectParameter("c", typeof(System.DateTime));
    
            var landusetypeParameter = landusetype.HasValue ?
                new ObjectParameter("landusetype", landusetype) :
                new ObjectParameter("landusetype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_DuesCalculationTillDate", rIDParameter, cParameter, landusetypeParameter);
        }
    
        public virtual ObjectResult<string> Sp_NewSchemereturn(Nullable<int> onlineapplicationid, Nullable<int> schemeid)
        {
            var onlineapplicationidParameter = onlineapplicationid.HasValue ?
                new ObjectParameter("Onlineapplicationid", onlineapplicationid) :
                new ObjectParameter("Onlineapplicationid", typeof(int));
    
            var schemeidParameter = schemeid.HasValue ?
                new ObjectParameter("schemeid", schemeid) :
                new ObjectParameter("schemeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Sp_NewSchemereturn", onlineapplicationidParameter, schemeidParameter);
        }
    
        public virtual ObjectResult<Sp_AccountReport_Result> Sp_AccountReport(string fY, Nullable<int> departmentId)
        {
            var fYParameter = fY != null ?
                new ObjectParameter("fY", fY) :
                new ObjectParameter("fY", typeof(string));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("departmentId", departmentId) :
                new ObjectParameter("departmentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_AccountReport_Result>("Sp_AccountReport", fYParameter, departmentIdParameter);
        }
    
        public virtual int Sp_DuesCalculationTillDate_20june2018(string rID, Nullable<System.DateTime> c, Nullable<int> landusetype)
        {
            var rIDParameter = rID != null ?
                new ObjectParameter("RID", rID) :
                new ObjectParameter("RID", typeof(string));
    
            var cParameter = c.HasValue ?
                new ObjectParameter("c", c) :
                new ObjectParameter("c", typeof(System.DateTime));
    
            var landusetypeParameter = landusetype.HasValue ?
                new ObjectParameter("landusetype", landusetype) :
                new ObjectParameter("landusetype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_DuesCalculationTillDate_20june2018", rIDParameter, cParameter, landusetypeParameter);
        }
    
        public virtual ObjectResult<Sp_DuesCalculationHistory_Result> Sp_DuesCalculationHistory(string rID, Nullable<System.DateTime> c, Nullable<int> landusetype)
        {
            var rIDParameter = rID != null ?
                new ObjectParameter("RID", rID) :
                new ObjectParameter("RID", typeof(string));
    
            var cParameter = c.HasValue ?
                new ObjectParameter("c", c) :
                new ObjectParameter("c", typeof(System.DateTime));
    
            var landusetypeParameter = landusetype.HasValue ?
                new ObjectParameter("landusetype", landusetype) :
                new ObjectParameter("landusetype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_DuesCalculationHistory_Result>("Sp_DuesCalculationHistory", rIDParameter, cParameter, landusetypeParameter);
        }
    
        public virtual ObjectResult<Sp_LeaseRentDuesCalculationTillDate_Result> Sp_LeaseRentDuesCalculationTillDate(string rID, Nullable<System.DateTime> c, Nullable<int> landusetype)
        {
            var rIDParameter = rID != null ?
                new ObjectParameter("RID", rID) :
                new ObjectParameter("RID", typeof(string));
    
            var cParameter = c.HasValue ?
                new ObjectParameter("c", c) :
                new ObjectParameter("c", typeof(System.DateTime));
    
            var landusetypeParameter = landusetype.HasValue ?
                new ObjectParameter("landusetype", landusetype) :
                new ObjectParameter("landusetype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_LeaseRentDuesCalculationTillDate_Result>("Sp_LeaseRentDuesCalculationTillDate", rIDParameter, cParameter, landusetypeParameter);
        }
    
        public virtual ObjectResult<Sp_DashboardPropertyData_Result> Sp_DashboardPropertyData(Nullable<int> deptId)
        {
            var deptIdParameter = deptId.HasValue ?
                new ObjectParameter("DeptId", deptId) :
                new ObjectParameter("DeptId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_DashboardPropertyData_Result>("Sp_DashboardPropertyData", deptIdParameter);
        }
    
        public virtual ObjectResult<Sp_ServiceReportDepartmentWise_Result> Sp_ServiceReportDepartmentWise(Nullable<int> departmentId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string requestthru)
        {
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("DepartmentId", departmentId) :
                new ObjectParameter("DepartmentId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var requestthruParameter = requestthru != null ?
                new ObjectParameter("requestthru", requestthru) :
                new ObjectParameter("requestthru", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ServiceReportDepartmentWise_Result>("Sp_ServiceReportDepartmentWise", departmentIdParameter, startDateParameter, endDateParameter, requestthruParameter);
        }
    
        public virtual ObjectResult<Sp_ManageaccountDetailDepartmentwise_Result> Sp_ManageaccountDetailDepartmentwise(Nullable<int> departmentId, Nullable<int> type)
        {
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("departmentId", departmentId) :
                new ObjectParameter("departmentId", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ManageaccountDetailDepartmentwise_Result>("Sp_ManageaccountDetailDepartmentwise", departmentIdParameter, typeParameter);
        }
    
        public virtual ObjectResult<Sp_GetListValueByTotalCount_Result> Sp_GetListValueByTotalCount(Nullable<int> departmentId, Nullable<int> reportTypeId)
        {
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("departmentId", departmentId) :
                new ObjectParameter("departmentId", typeof(int));
    
            var reportTypeIdParameter = reportTypeId.HasValue ?
                new ObjectParameter("reportTypeId", reportTypeId) :
                new ObjectParameter("reportTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetListValueByTotalCount_Result>("Sp_GetListValueByTotalCount", departmentIdParameter, reportTypeIdParameter);
        }
    
        public virtual ObjectResult<Sp_ManageDuuesDetailDepartmentwise_Result> Sp_ManageDuuesDetailDepartmentwise(Nullable<System.DateTime> date, Nullable<int> departmentId, Nullable<int> type)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var departmentIdParameter = departmentId.HasValue ?
                new ObjectParameter("departmentId", departmentId) :
                new ObjectParameter("departmentId", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ManageDuuesDetailDepartmentwise_Result>("Sp_ManageDuuesDetailDepartmentwise", dateParameter, departmentIdParameter, typeParameter);
        }
    }
}
