//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OSMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OSMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NA.PMS.OnlineScheme.Resources.OSMessages", typeof(OSMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The allotment letter dated {0} have been dispatched..
        /// </summary>
        public static string AllotmentLetter {
            get {
                return ResourceManager.GetString("AllotmentLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T and C in the AL dtd 12Mar2018 have been rectified as per Brochure. Corrigendum Letter are being dispatched. Other T and C of AL shall remain the same..
        /// </summary>
        public static string AllotmentLetterTC01 {
            get {
                return ResourceManager.GetString("AllotmentLetterTC01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Allottee list of scheme {0} deptment has been submitted. Regards, http://mynoida.in.
        /// </summary>
        public static string AllotteeListSuccess {
            get {
                return ResourceManager.GetString("AllotteeListSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your application for {0} has been accepted. Kindly connect with NOIDA Authority. Regards, http://mynoida.in.
        /// </summary>
        public static string AppAccepted {
            get {
                return ResourceManager.GetString("AppAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your application number of NOIDA for {0} has been rejected. Kindly check the status online at mynoida.in. Regards, http://mynoida.in.
        /// </summary>
        public static string AppRejected {
            get {
                return ResourceManager.GetString("AppRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your Completion Request has been submitted. Regards, http://mynoida.in.
        /// </summary>
        public static string CompletionReqSubmit {
            get {
                return ResourceManager.GetString("CompletionReqSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, your covid 19 pass no: {0}  has been {1} successfully. Regards Noida Authority..
        /// </summary>
        public static string CovidPassStatus {
            get {
                return ResourceManager.GetString("CovidPassStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of any discrepancies please contact Noida Authority. Thanks and Regards, http://mynoida.in.
        /// </summary>
        public static string Discrepancy {
            get {
                return ResourceManager.GetString("Discrepancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Applicant, Details of venue and time of reporting for draw Industrial Scheme code {0} have been updated on website, please check..
        /// </summary>
        public static string DrawVenueUpdate {
            get {
                return ResourceManager.GetString("DrawVenueUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, payment is due for property {0}. Request you to pay. Pl ignore if already paid. Contact Noida Authority in case of any discrepancy..
        /// </summary>
        public static string DuesPaymentReminder {
            get {
                return ResourceManager.GetString("DuesPaymentReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Applicant, duplicate accounts have been identified, kindly check the list on Authority website and visit Authority to clarify and submit proof of payment..
        /// </summary>
        public static string DuplicatePayAccount {
            get {
                return ResourceManager.GetString("DuplicatePayAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Applicant,
        ///Your payment against Industrial Plot Allotment Scheme {0} has been {1}.
        ///Please send email to {2} in case of any discrepancy along with supporting documents. Regards, Noida Authority.
        /// </summary>
        public static string Email_StatusAfterPaymentValidation {
            get {
                return ResourceManager.GetString("Email_StatusAfterPaymentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Applicant,
        ///Your payment against Industrial Plot Allotment Scheme {0} has been {1}.
        ///Please send email to industry@noidaauthorityonline.com in case of any discrepancy along with supporting documents. Regards, Noida Authority.
        /// </summary>
        public static string EmailForSchemeFormUpdate {
            get {
                return ResourceManager.GetString("EmailForSchemeFormUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application no {0} is completed. Please visit website {1} for details. Date of draw shall be informed separately.
        /// </summary>
        public static string ForCompleteForm {
            get {
                return ResourceManager.GetString("ForCompleteForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of application against Industrial scheme uploaded on NOIDA website. In case of any discrepancy, report immediately to NOIDA Industrial Department..
        /// </summary>
        public static string ForDiscrepancyForm {
            get {
                return ResourceManager.GetString("ForDiscrepancyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your application no {0} is incomplete. Please visit website {1} . Please upload required documents by 5 PM on 2nd Dec.
        /// </summary>
        public static string ForIncompleteForm {
            get {
                return ResourceManager.GetString("ForIncompleteForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Functional Request has been approved. Kindly clear all your Dues..
        /// </summary>
        public static string FunctionalReqApprove {
            get {
                return ResourceManager.GetString("FunctionalReqApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Functional Request has been cancelled..
        /// </summary>
        public static string FunctionalReqCancel {
            get {
                return ResourceManager.GetString("FunctionalReqCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Functional Request has been rejected..
        /// </summary>
        public static string FunctionalReqReject {
            get {
                return ResourceManager.GetString("FunctionalReqReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Functional Request has been re-submitted..
        /// </summary>
        public static string FunctionalReqResubmit {
            get {
                return ResourceManager.GetString("FunctionalReqResubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Functional Request has been saved..
        /// </summary>
        public static string FunctionalReqSave {
            get {
                return ResourceManager.GetString("FunctionalReqSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Interview Request has been removed..
        /// </summary>
        public static string InterviewReqRemove {
            get {
                return ResourceManager.GetString("InterviewReqRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Interview Request has been saved..
        /// </summary>
        public static string InterviewReqSave {
            get {
                return ResourceManager.GetString("InterviewReqSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Interview Request has been updated..
        /// </summary>
        public static string InterviewReqUpdate {
            get {
                return ResourceManager.GetString("InterviewReqUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear applicant, regarding your form no {0} against scheme {1}, we found mismatch in payment info updated by you. Kindly refer further info.
        /// </summary>
        public static string IPSchemePaymentInfoU1 {
            get {
                return ResourceManager.GetString("IPSchemePaymentInfoU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly refer your registered email or visit Industrial Department in NOIDA Authority or send email at {0} latest by {1}..
        /// </summary>
        public static string IPSchemePaymentInfoU2 {
            get {
                return ResourceManager.GetString("IPSchemePaymentInfoU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your KYA Form against Reference No {0} has been approved with KYA Uid {1}. Thanks and Regards, http://mynoida.in.
        /// </summary>
        public static string KYAApproved {
            get {
                return ResourceManager.GetString("KYAApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your OTP for KYA Form is {0}. DO NOT disclose this OTP to anyone. This is for online use by you only. Regards, http://mynoida.in.
        /// </summary>
        public static string KYAOTP {
            get {
                return ResourceManager.GetString("KYAOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your KYA Form against Reference No {0} has been rejected. In case of any discrepancies please contact Noida Authority..
        /// </summary>
        public static string KYARejected {
            get {
                return ResourceManager.GetString("KYARejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your KYA Form has been submitted successfully with Reference No {0}. We assure our best services. Thanks and Regards, http://mynoida.in.
        /// </summary>
        public static string KYASubmitted {
            get {
                return ResourceManager.GetString("KYASubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Mutation Request has been rejected..
        /// </summary>
        public static string MuattionReqReject {
            get {
                return ResourceManager.GetString("MuattionReqReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Mutation Request has been cancelled..
        /// </summary>
        public static string MutationReqCancel {
            get {
                return ResourceManager.GetString("MutationReqCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Mutation Request has been submitted..
        /// </summary>
        public static string MutationReqSubmit {
            get {
                return ResourceManager.GetString("MutationReqSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Refreshed. Redirected to scheme information page..
        /// </summary>
        public static string OAFPageRefresh {
            get {
                return ResourceManager.GetString("OAFPageRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment is unsuccessful..
        /// </summary>
        public static string OAFPaymentError {
            get {
                return ResourceManager.GetString("OAFPaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment is successful..
        /// </summary>
        public static string OAFPaymentSuccess {
            get {
                return ResourceManager.GetString("OAFPaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your application no {0} submitted success fully. Kindly check the document list on mynoida.in Regards, http://mynoida.in.
        /// </summary>
        public static string OfflineAppReqSuccess {
            get {
                return ResourceManager.GetString("OfflineAppReqSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application received against {0} has been uploaded on authority website, kindly contact industry department in case of any discrepancies..
        /// </summary>
        public static string OnlineApplication {
            get {
                return ResourceManager.GetString("OnlineApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pl check the eligibility list for the{0}and clarification on the list published on {1} on website. Contact Industry deptt for any query.
        /// </summary>
        public static string OnlineApplication01 {
            get {
                return ResourceManager.GetString("OnlineApplication01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, your challan has been validated for Application Form {0}. Now Print your Application Form. Thanks and Regards. Noida Authority.
        /// </summary>
        public static string OnlineApplicationChallanStatus {
            get {
                return ResourceManager.GetString("OnlineApplicationChallanStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Application Form fee {0} has been paid successfully. Regards, http://mynoida.in.
        /// </summary>
        public static string OnlineApplicationFormFee {
            get {
                return ResourceManager.GetString("OnlineApplicationFormFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your Application Form {0} has been updated successfully. We assure our best services.Thanks and Regards. Noida Authority.
        /// </summary>
        public static string OnlineApplicationFormUpdate {
            get {
                return ResourceManager.GetString("OnlineApplicationFormUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your online Application form OTP is {0}. Regards, http:http://mynoida.in.
        /// </summary>
        public static string OnlineApplicationOTP {
            get {
                return ResourceManager.GetString("OnlineApplicationOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your previous challan validated for Application Form {0}. Now Print your Application Form.Thanks and Regards. Noida Authority.
        /// </summary>
        public static string OnlineApplicationPreChallanStatus {
            get {
                return ResourceManager.GetString("OnlineApplicationPreChallanStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your Application Form has been rejected successfully. We assure you of our best services always. Thanks and Regards. Noida Authority..
        /// </summary>
        public static string OnlineApplicationRejected {
            get {
                return ResourceManager.GetString("OnlineApplicationRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your Application Form has been submitted successfully with Form No {0} We assure our best services. Thanks and Regards. Noida Authority..
        /// </summary>
        public static string OnlineApplicationSubmitted {
            get {
                return ResourceManager.GetString("OnlineApplicationSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your Application Form has been submitted successfully with Form No {0} We assure our best services. Thanks and Regards. Noida Authority..
        /// </summary>
        public static string OnlineApplicationSubmitted1 {
            get {
                return ResourceManager.GetString("OnlineApplicationSubmitted1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your online application request has been submit sucessfully..
        /// </summary>
        public static string OnlineAppReqSuccess {
            get {
                return ResourceManager.GetString("OnlineAppReqSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, OTP for payment of form no {0} is {1}. Regards, http:http://mynoida.in.
        /// </summary>
        public static string OnlinePaymentOTP {
            get {
                return ResourceManager.GetString("OnlinePaymentOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Processing fee for {0} against request id {1} of amount {2} has been paid successfully, Noida Authority.
        /// </summary>
        public static string OnlineProcessingFee {
            get {
                return ResourceManager.GetString("OnlineProcessingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding reservation letter issued against the scheme {0} submit self-attested documents to support your application by {1}.
        /// </summary>
        public static string OnlineSchemeInfo1 {
            get {
                return ResourceManager.GetString("OnlineSchemeInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed allotment letter along with payment plan will be issued only after verification of the documents. Regards, Noida Authority.
        /// </summary>
        public static string OnlineSchemeInfo2 {
            get {
                return ResourceManager.GetString("OnlineSchemeInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your online service request has been submitted successfully with request no is {0}. Regards, http:http://mynoida.in.
        /// </summary>
        public static string OnlineServiceRequest {
            get {
                return ResourceManager.GetString("OnlineServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final list against {0} has been uploaded on website, kindly check status.
        ///Contact department for any query or discrepancies. NOIDA.
        /// </summary>
        public static string OnlineTransportScheme201805 {
            get {
                return ResourceManager.GetString("OnlineTransportScheme201805", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, You are successfully registered with mynoida.in. Your user name is {0} and password is {1} Regards, http://mynoida.in.
        /// </summary>
        public static string OnlineUserRegistration {
            get {
                return ResourceManager.GetString("OnlineUserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OTP is {0}. DO NOT disclose this to anyone by any means. This is for online use by you only..
        /// </summary>
        public static string OTPForOffline {
            get {
                return ResourceManager.GetString("OTPForOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your OTP is {0}. DO NOT disclose this OTP to anyone. This is for online use by you only. Regards, http://mynoida.in.
        /// </summary>
        public static string OTPSend {
            get {
                return ResourceManager.GetString("OTPSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, You have successfully changed your password. Your new password is {0}. Regards, http://mynoida.in.
        /// </summary>
        public static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear applicant, this mail has reference regarding your participation in the industrial land allotment scheme. We have found mismatch regarding the payments details like UTR information submitted by you and details received from the bank. Detailed information has been updated on the website www.noidaauthorityonline.in.  Without confirmation of the payment details your application shall not be considered for further processing and would be rejected. Kindly visit the industry department in NOIDA Authority offi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PaymentMismatchEmail {
            get {
                return ResourceManager.GetString("PaymentMismatchEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User,&lt;br&gt;&lt;br&gt;Your account has been deactivated. &lt;br&gt; Regards, http://mynoida.in.
        /// </summary>
        public static string PIS_Account_Deactivated_Email {
            get {
                return ResourceManager.GetString("PIS_Account_Deactivated_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your account has been deactivated. Regards, http://mynoida.in.
        /// </summary>
        public static string PIS_Account_Deactivated_SMS {
            get {
                return ResourceManager.GetString("PIS_Account_Deactivated_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User,&lt;br&gt;&lt;br&gt;Due to {0} Your Application has been rejected. &lt;br&gt; Regards, http://mynoida.in.
        /// </summary>
        public static string PIS_App_Rejected_Email {
            get {
                return ResourceManager.GetString("PIS_App_Rejected_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Due to {0} Your Application has been rejected. Regards, http://mynoida.in.
        /// </summary>
        public static string PIS_App_Rejected_SMS {
            get {
                return ResourceManager.GetString("PIS_App_Rejected_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your OTP is {0} DO NOT disclose this OTP to anyone. This is for online use by you only. Regards, http://mynoida.in.
        /// </summary>
        public static string PIS_otp {
            get {
                return ResourceManager.GetString("PIS_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User,&lt;br&gt;&lt;br&gt;You have successfully changed your password. Your new password is {0}. DO NOT disclose this to anyone by any means.&lt;br&gt;Regards, http://mynoida.in.
        /// </summary>
        public static string PIS_PasswordChanges_Email {
            get {
                return ResourceManager.GetString("PIS_PasswordChanges_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, You have successfully changed your password. Your new password is {0} Regards, http://mynoida.in.
        /// </summary>
        public static string PIS_PasswordChanges_SMS {
            get {
                return ResourceManager.GetString("PIS_PasswordChanges_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Registration Process has been completed successfully..
        /// </summary>
        public static string PIS_registration_1 {
            get {
                return ResourceManager.GetString("PIS_registration_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi,&lt;br&gt;&lt;br&gt;A new User has registered with resgistration no. {0} . Please check and reply..
        /// </summary>
        public static string PIS_registration_2 {
            get {
                return ResourceManager.GetString("PIS_registration_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, You are successfully registered with mynoida.in. Your user name is {0} and password is {1} Regards, http://mynoida.in.
        /// </summary>
        public static string PIS_Registration_Activation {
            get {
                return ResourceManager.GetString("PIS_Registration_Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the property area and collect your Possession Letter within 15 days..
        /// </summary>
        public static string PossessionLetter {
            get {
                return ResourceManager.GetString("PossessionLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Permission Request has been cancelled of Registration id: {0}..
        /// </summary>
        public static string RentPermissionCancel {
            get {
                return ResourceManager.GetString("RentPermissionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Permission Request has been approved of Registration id: {0}..
        /// </summary>
        public static string RentPermissionReqApprove {
            get {
                return ResourceManager.GetString("RentPermissionReqApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Permission Request has been rejected of Registration id: {0}..
        /// </summary>
        public static string RentPermissionReqReject {
            get {
                return ResourceManager.GetString("RentPermissionReqReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Permission Request has been resubmitted for approval of Registration id: {0}..
        /// </summary>
        public static string RentPermissionReqResubmit {
            get {
                return ResourceManager.GetString("RentPermissionReqResubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Permission Request has been submitted for approval of Registration id: {0}. .
        /// </summary>
        public static string RentPermissionReqSubmit {
            get {
                return ResourceManager.GetString("RentPermissionReqSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Applicant, The final eligibility list for Industrial Scheme code {0} is live on authority website. Kindly check, Date of Draw {1}.
        /// </summary>
        public static string SchemeDrawMessage {
            get {
                return ResourceManager.GetString("SchemeDrawMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund of unsuccessful applicant against {0} have been processed to accounts mentioned in the application forms, Noida Authority.
        /// </summary>
        public static string SchemeRefundInfo01 {
            get {
                return ResourceManager.GetString("SchemeRefundInfo01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please mail at {0}  incase refund not received by today EOD, Noida Authority.
        /// </summary>
        public static string SchemeRefundInfo02 {
            get {
                return ResourceManager.GetString("SchemeRefundInfo02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your online service request {0} has been {1}. Regards, http://mynoida.in.
        /// </summary>
        public static string SDServiceReqStatusChange {
            get {
                return ResourceManager.GetString("SDServiceReqStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your online service request has been updated successfully with request no is {0}. Regards, http:http://mynoida.in.
        /// </summary>
        public static string SDServiceReqUpdate {
            get {
                return ResourceManager.GetString("SDServiceReqUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, You have successfully registered with www.mynoida.in. Your Username is: {0} and Password is {1}. Regards,http://mynoida.in.
        /// </summary>
        public static string SendCredentials {
            get {
                return ResourceManager.GetString("SendCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your service request {0} has been {1}. Regards, http://mynoida.in.
        /// </summary>
        public static string ServiceReqStatusChange {
            get {
                return ResourceManager.GetString("ServiceReqStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Applicant, status of your scheme form no. {0} is {1}. Contact Noida Authority for any discrepancy. Regards, Noida Authority.
        /// </summary>
        public static string SMS_SchemeFormStatus {
            get {
                return ResourceManager.GetString("SMS_SchemeFormStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Applicant, Kindly check the status of your application on Authority website. Pl send an email at industry@noidaauthorityonline.com for any discrepancy..
        /// </summary>
        public static string SMS_SchemeFormStatusUpdate {
            get {
                return ResourceManager.GetString("SMS_SchemeFormStatusUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pl refer to your form against IP scheme {0}, scrutiny result has been sent to your reg email-id. Kindly check and send requisite docs by {1}.
        /// </summary>
        public static string SMS_ScrutinyMsg {
            get {
                return ResourceManager.GetString("SMS_ScrutinyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Applicant, Updated status of your online form against Industrial Scheme {0} has been sent on your email id. Kindly check your status..
        /// </summary>
        public static string SMS_StatusAfterPaymentValidation {
            get {
                return ResourceManager.GetString("SMS_StatusAfterPaymentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Applicant, 
        ///Updated status of your online form against Industrial Scheme {0} has been sent on your email id. Kindly check your status..
        /// </summary>
        public static string SMSforSchemeFormUpdate {
            get {
                return ResourceManager.GetString("SMSforSchemeFormUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Applicant {0} status uploaded on NOIDA website. Please check official website {1}.
        /// </summary>
        public static string StatusOnWebsite {
            get {
                return ResourceManager.GetString("StatusOnWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Unsuccessful List of Scheme {0} has been submitted for Approval. Regards, http://mynoida.in.
        /// </summary>
        public static string UnsuccessfulListSuccess {
            get {
                return ResourceManager.GetString("UnsuccessfulListSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is uploaded successfully for application no {0}. Regards, mynoida.in.
        /// </summary>
        public static string UploadDocumentSuccess {
            get {
                return ResourceManager.GetString("UploadDocumentSuccess", resourceCulture);
            }
        }
    }
}
