//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challan_Trans
    {
        public int Id { get; set; }
        public Nullable<int> Rid { get; set; }
        public Nullable<int> Challan_Master_Id { get; set; }
        public Nullable<int> Head_Id { get; set; }
        public Nullable<int> Subhead_Id { get; set; }
        public Nullable<int> EmployeeCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Challan_Master Challan_Master { get; set; }
    }
}
