//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineFirmDirectorMaster
    {
        public int CidSid { get; set; }
        public int RequestNo { get; set; }
        public Nullable<int> Rid { get; set; }
        public string DirectorName { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> DirectorShare { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ApplicationId { get; set; }
    
        public virtual Customer_ServiceRequest Customer_ServiceRequest { get; set; }
    }
}
