//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineApplicationDetails_trans
    {
        public int AutoID { get; set; }
        public Nullable<int> ServiceRefId { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public string TrKey { get; set; }
        public string txnid { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string GetwayName { get; set; }
        public string productinfo { get; set; }
        public string udf1 { get; set; }
        public string udf2 { get; set; }
        public string udf3 { get; set; }
        public string udf4 { get; set; }
        public string udf5 { get; set; }
        public string mihpayid { get; set; }
        public string mode { get; set; }
        public Nullable<int> TranStatus { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string payment_source { get; set; }
        public string PG_Type { get; set; }
        public string bank_ref_num { get; set; }
        public string bankcode { get; set; }
        public string error { get; set; }
        public string error_Message { get; set; }
        public string name_on_card { get; set; }
        public string cardnum { get; set; }
        public string cardhash { get; set; }
        public string issuing_bank { get; set; }
        public string card_type { get; set; }
        public Nullable<System.DateTime> modifiydate { get; set; }
        public string virtualaccountno { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<int> OnlineRequestId { get; set; }
        public string ChallanId { get; set; }
        public string ChallanRefId { get; set; }
        public string hash_sequence { get; set; }
    }
}
