//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentLeaseRentMaster
    {
        public int Id { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public string Applicant { get; set; }
        public string Sector { get; set; }
        public string Block { get; set; }
        public string PlotNo { get; set; }
        public Nullable<System.DateTime> LeaseDeedDate { get; set; }
        public Nullable<System.DateTime> TransferLeaseDate { get; set; }
        public Nullable<decimal> PenalInterest { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> TotalPremium { get; set; }
        public Nullable<System.DateTime> NDCDate { get; set; }
        public string NDCStatus { get; set; }
        public Nullable<bool> IsOneTimeLeasePaid { get; set; }
        public Nullable<bool> IsTotalLeasePaid { get; set; }
        public Nullable<bool> IsOneTimeInstallmentPaid { get; set; }
        public Nullable<bool> IsTotalInstallmentPaid { get; set; }
        public Nullable<decimal> DuesAmount { get; set; }
        public Nullable<System.DateTime> DuesUptoDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
