//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentLeaseRentTran
    {
        public int Id { get; set; }
        public Nullable<int> RentId { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<decimal> LeaseRentPremium { get; set; }
        public Nullable<System.DateTime> DepositDueDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Approver { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string PaymentMode { get; set; }
        public string TransactionId { get; set; }
        public Nullable<decimal> DuesAmount { get; set; }
        public Nullable<System.DateTime> DuesUptoDate { get; set; }
        public string HtmlDuesTemplate { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual LeaseRentPayment LeaseRentPayment { get; set; }
    }
}
