//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemeCostTran
    {
        public Nullable<int> schemeId { get; set; }
        public Nullable<int> departmentId { get; set; }
        public Nullable<int> propertyTypeId { get; set; }
        public Nullable<int> sectorId { get; set; }
        public Nullable<int> floorId { get; set; }
        public Nullable<int> blockId { get; set; }
        public int refId { get; set; }
        public Nullable<decimal> landRatePerSqmt { get; set; }
        public Nullable<decimal> propertyCost { get; set; }
        public Nullable<decimal> totalPropertyCost { get; set; }
        public Nullable<decimal> civilCost { get; set; }
        public Nullable<decimal> allotmentMoney { get; set; }
        public Nullable<decimal> earnestMoney { get; set; }
        public Nullable<decimal> leaseRent { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual BlockMst BlockMst { get; set; }
        public virtual DepartmentMst DepartmentMst { get; set; }
        public virtual FloorMst FloorMst { get; set; }
        public virtual SchemeMst SchemeMst { get; set; }
        public virtual SectorMst SectorMst { get; set; }
    }
}
