//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_cal
    {
        public Nullable<decimal> InstallmentAmount { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public Nullable<System.DateTime> InstallmentDueDate { get; set; }
        public Nullable<System.DateTime> NextDate { get; set; }
        public Nullable<System.DateTime> PreviousDate { get; set; }
        public Nullable<decimal> DuesTill { get; set; }
        public Nullable<System.DateTime> CI { get; set; }
        public Nullable<decimal> DuesNextWithInterest { get; set; }
        public Nullable<decimal> PenalAmount { get; set; }
        public Nullable<int> NewDateDiff { get; set; }
        public Nullable<decimal> TotalPanelAmount { get; set; }
        public Nullable<decimal> TotalPrincipalAmount { get; set; }
        public string DepositDate { get; set; }
        public Nullable<int> rid { get; set; }
    }
}
