//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidatedPropertyDetailMst
    {
        public int Id { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public string PlotNo { get; set; }
        public Nullable<bool> IsValidatedByOrganisation { get; set; }
        public Nullable<int> OrganisationValidatorId { get; set; }
        public Nullable<System.DateTime> OrganisationValidationDate { get; set; }
        public Nullable<bool> IsValidatedByDepartment { get; set; }
        public Nullable<int> DepartmentValidatorId { get; set; }
        public Nullable<System.DateTime> DepartmentValidationDate { get; set; }
        public Nullable<bool> IsValidatedByAccounts { get; set; }
        public Nullable<int> AccountsValidatorId { get; set; }
        public Nullable<System.DateTime> AccountsValidationDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> UpdationCount { get; set; }
        public Nullable<int> OptionalId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
