//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.NICService.NiveshMitraDistrictTestApiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NiveshMitraDistrictTestApiService.Dist_updation_after_land_allotmt_By_DptSoap")]
    public interface Dist_updation_after_land_allotmt_By_DptSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Unit_Industry_District_Location_Updation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Unit_Industry_District_Location_Updation(string Dept_ID, string UnitID, string Dist_Code, string Address_Max_200_char, string PIN, string paskey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Unit_Industry_District_Location_Updation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Unit_Industry_District_Location_UpdationAsync(string Dept_ID, string UnitID, string Dist_Code, string Address_Max_200_char, string PIN, string paskey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Dist_updation_after_land_allotmt_By_DptSoapChannel : NA.PMS.NICService.NiveshMitraDistrictTestApiService.Dist_updation_after_land_allotmt_By_DptSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Dist_updation_after_land_allotmt_By_DptSoapClient : System.ServiceModel.ClientBase<NA.PMS.NICService.NiveshMitraDistrictTestApiService.Dist_updation_after_land_allotmt_By_DptSoap>, NA.PMS.NICService.NiveshMitraDistrictTestApiService.Dist_updation_after_land_allotmt_By_DptSoap {
        
        public Dist_updation_after_land_allotmt_By_DptSoapClient() {
        }
        
        public Dist_updation_after_land_allotmt_By_DptSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Dist_updation_after_land_allotmt_By_DptSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Dist_updation_after_land_allotmt_By_DptSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Dist_updation_after_land_allotmt_By_DptSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Unit_Industry_District_Location_Updation(string Dept_ID, string UnitID, string Dist_Code, string Address_Max_200_char, string PIN, string paskey) {
            return base.Channel.Unit_Industry_District_Location_Updation(Dept_ID, UnitID, Dist_Code, Address_Max_200_char, PIN, paskey);
        }
        
        public System.Threading.Tasks.Task<string> Unit_Industry_District_Location_UpdationAsync(string Dept_ID, string UnitID, string Dist_Code, string Address_Max_200_char, string PIN, string paskey) {
            return base.Channel.Unit_Industry_District_Location_UpdationAsync(Dept_ID, UnitID, Dist_Code, Address_Max_200_char, PIN, paskey);
        }
    }
}
