//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllDefaulterList
    {
        public int Id { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<decimal> LeaserentDuesAmount { get; set; }
        public Nullable<decimal> LeaserentInterestAmount { get; set; }
        public string LeaserentPaidupto { get; set; }
        public Nullable<decimal> InstallmentDuesAmount { get; set; }
        public Nullable<int> NoOfInstallment { get; set; }
        public Nullable<System.DateTime> CalculationDate { get; set; }
        public Nullable<decimal> InstallmentAmount { get; set; }
        public Nullable<decimal> PenalInstallmentIntrestAmount { get; set; }
        public string Default1 { get; set; }
        public string Default2 { get; set; }
        public string Default3 { get; set; }
        public string Default4 { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string InstPaidUpto { get; set; }
    }
}
