//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CircleRateMst
    {
        public Nullable<int> sectorId { get; set; }
        public Nullable<int> blockId { get; set; }
        public Nullable<int> departmentId { get; set; }
        public Nullable<int> propertyTypeId { get; set; }
        public int refId { get; set; }
        public Nullable<decimal> circleRate { get; set; }
        public string unit { get; set; }
        public Nullable<System.DateTime> effectiveFrom { get; set; }
        public Nullable<System.DateTime> effectiveTo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual BlockMst BlockMst { get; set; }
        public virtual DepartmentMst DepartmentMst { get; set; }
    }
}
