//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Completion_Details
    {
        public int Id { get; set; }
        public Nullable<int> Rid { get; set; }
        public string Property_Number { get; set; }
        public Nullable<System.DateTime> Completion_Due_Date { get; set; }
        public Nullable<System.DateTime> Completion_Execution_date { get; set; }
        public string Extension { get; set; }
        public string Completion_Type { get; set; }
        public Nullable<decimal> Part_Completion_Percent { get; set; }
        public Nullable<decimal> Part_Completion_Area { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<decimal> Completion_Charge { get; set; }
    }
}
