//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_ServiceRequestDocument
    {
        public int Id { get; set; }
        public Nullable<int> ServiceRequestRefId { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public Nullable<int> DispatchNo { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsDigitalSigned { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UploadedDocument { get; set; }
        public string DocumentType { get; set; }
        public string DocumentName { get; set; }
        public string DocumentPath { get; set; }
        public Nullable<int> UploadStatusId { get; set; }
        public Nullable<int> RequestorId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DocumentRefId { get; set; }
    }
}
