//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentMst
    {
        public DepartmentMst()
        {
            this.AlloteeListMasters = new HashSet<AlloteeListMaster>();
            this.ApplicationDetails = new HashSet<ApplicationDetail>();
            this.CircleRateMsts = new HashSet<CircleRateMst>();
            this.Letter_Signing_Authority = new HashSet<Letter_Signing_Authority>();
            this.InterestMsts = new HashSet<InterestMst>();
            this.PropertyTypeMsts = new HashSet<PropertyTypeMst>();
            this.SchemeDepartmentTrans = new HashSet<SchemeDepartmentTran>();
            this.SchemeQuotaTrans = new HashSet<SchemeQuotaTran>();
            this.SchemeRebateTrans = new HashSet<SchemeRebateTran>();
            this.UnsuccessfulApplicantListMasters = new HashSet<UnsuccessfulApplicantListMaster>();
            this.TemplateMasters = new HashSet<TemplateMaster>();
            this.Letter_History_new = new HashSet<Letter_History_new>();
            this.AllotmentMasters = new HashSet<AllotmentMaster>();
            this.SchemeCostTrans = new HashSet<SchemeCostTran>();
            this.SchemePropTrans = new HashSet<SchemePropTran>();
            this.PropertyCompensationMsts = new HashSet<PropertyCompensationMst>();
            this.Letter_History = new HashSet<Letter_History>();
        }
    
        public int departmentId { get; set; }
        public string departmentName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual ICollection<AlloteeListMaster> AlloteeListMasters { get; set; }
        public virtual ICollection<ApplicationDetail> ApplicationDetails { get; set; }
        public virtual ICollection<CircleRateMst> CircleRateMsts { get; set; }
        public virtual ICollection<Letter_Signing_Authority> Letter_Signing_Authority { get; set; }
        public virtual ICollection<InterestMst> InterestMsts { get; set; }
        public virtual ICollection<PropertyTypeMst> PropertyTypeMsts { get; set; }
        public virtual ICollection<SchemeDepartmentTran> SchemeDepartmentTrans { get; set; }
        public virtual ICollection<SchemeQuotaTran> SchemeQuotaTrans { get; set; }
        public virtual ICollection<SchemeRebateTran> SchemeRebateTrans { get; set; }
        public virtual ICollection<UnsuccessfulApplicantListMaster> UnsuccessfulApplicantListMasters { get; set; }
        public virtual ICollection<TemplateMaster> TemplateMasters { get; set; }
        public virtual ICollection<Letter_History_new> Letter_History_new { get; set; }
        public virtual ICollection<AllotmentMaster> AllotmentMasters { get; set; }
        public virtual ICollection<SchemeCostTran> SchemeCostTrans { get; set; }
        public virtual ICollection<SchemePropTran> SchemePropTrans { get; set; }
        public virtual ICollection<PropertyCompensationMst> PropertyCompensationMsts { get; set; }
        public virtual ICollection<Letter_History> Letter_History { get; set; }
    }
}
