//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpassMaster
    {
        public int Id { get; set; }
        public string EpassNo { get; set; }
        public string EpassType { get; set; }
        public string Applicant { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string LocalPlace { get; set; }
        public string PIN { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Purpose { get; set; }
        public string VehicleType { get; set; }
        public string VehicleNo { get; set; }
        public string RCNo { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string PhotoPath { get; set; }
        public string UserIdPath { get; set; }
        public string RCPath { get; set; }
        public string LicencePath { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string Approver { get; set; }
        public string Comment { get; set; }
        public string EPDI { get; set; }
        public string EPDII { get; set; }
        public string EPDIII { get; set; }
        public string EPDIV { get; set; }
        public string EPDV { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
