//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEAD_MASTER
    {
        public HEAD_MASTER()
        {
            this.HEAD_SUB_MASTER = new HashSet<HEAD_SUB_MASTER>();
            this.RECIEPT_HEAD = new HashSet<RECIEPT_HEAD>();
        }
    
        public int HEAD_CODE { get; set; }
        public string HEAD_NAME { get; set; }
        public Nullable<decimal> BUDGET_AMOUNT { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
    
        public virtual ICollection<HEAD_SUB_MASTER> HEAD_SUB_MASTER { get; set; }
        public virtual ICollection<RECIEPT_HEAD> RECIEPT_HEAD { get; set; }
    }
}
