//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallmentDuesPayment
    {
        public InstallmentDuesPayment()
        {
            this.InstallmentDuesPaymentTrans = new HashSet<InstallmentDuesPaymentTran>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public string Applicant { get; set; }
        public string Sector { get; set; }
        public string Block { get; set; }
        public string PlotNo { get; set; }
        public Nullable<decimal> InstallmentAmount { get; set; }
        public Nullable<System.DateTime> InstallmentStartDate { get; set; }
        public Nullable<System.DateTime> InstallmentEndDate { get; set; }
        public Nullable<decimal> PenalInterest { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<System.DateTime> NDCDate { get; set; }
        public string NDCStatus { get; set; }
        public Nullable<bool> IsOneTimeLeasePaid { get; set; }
        public Nullable<bool> IsTotalPremiumPaid { get; set; }
        public Nullable<decimal> DuesAmount { get; set; }
        public Nullable<decimal> PreviousDues { get; set; }
        public Nullable<decimal> CurrentDues { get; set; }
        public Nullable<decimal> GstAmount { get; set; }
        public Nullable<System.DateTime> DuesUptoDate { get; set; }
        public Nullable<System.DateTime> PreviousDuesDate { get; set; }
        public Nullable<System.DateTime> CurrentDuesDate { get; set; }
        public string PaymentMode { get; set; }
        public string TransactionId { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<decimal> BalanceInterest { get; set; }
        public Nullable<System.DateTime> BalanceUptoDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<int> InstallmentNo { get; set; }
        public Nullable<int> LastPaidInstallmentNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Approver { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string RComment { get; set; }
        public Nullable<System.DateTime> RCommentDate { get; set; }
        public string HtmlDuesTemplate { get; set; }
    
        public virtual ICollection<InstallmentDuesPaymentTran> InstallmentDuesPaymentTrans { get; set; }
    }
}
