//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestMst
    {
        public int refId { get; set; }
        public Nullable<int> departmentId { get; set; }
        public Nullable<decimal> normalInterest { get; set; }
        public Nullable<decimal> penalInterest { get; set; }
        public Nullable<System.DateTime> effectedFrom { get; set; }
        public Nullable<System.DateTime> effectedTo { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual DepartmentMst DepartmentMst { get; set; }
    }
}
