//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupDepartment
    {
        public int Id { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ConstructionPeriodAllowed { get; set; }
    }
}
