//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noting_File_Master
    {
        public Noting_File_Master()
        {
            this.Noting_File_Trans = new HashSet<Noting_File_Trans>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Rid { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public string File_Number { get; set; }
        public Nullable<int> Receive_By { get; set; }
        public Nullable<System.DateTime> Receive_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual ICollection<Noting_File_Trans> Noting_File_Trans { get; set; }
    }
}
