//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineApplicationProcessDetail
    {
        public int Id { get; set; }
        public Nullable<int> OnlineApplicationId { get; set; }
        public Nullable<int> ApplicationStatus { get; set; }
        public Nullable<int> ProcessStatus { get; set; }
        public string Status { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<int> Approver { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual OnlineApplicationDetail OnlineApplicationDetail { get; set; }
    }
}
