//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineCheckLisTran
    {
        public int id { get; set; }
        public Nullable<int> onlineapplicationId { get; set; }
        public Nullable<int> CheckListId { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FileNAme { get; set; }
    
        public virtual OnlineApplicationDetail OnlineApplicationDetail { get; set; }
        public virtual OnlineCheckListMaster OnlineCheckListMaster { get; set; }
    }
}
