//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineFirmRequestMaster
    {
        public int FirmSid { get; set; }
        public int RequestNo { get; set; }
        public Nullable<int> Rid { get; set; }
        public string OldFirmName { get; set; }
        public string NewFirmName { get; set; }
        public Nullable<int> OldFirmStatus { get; set; }
        public Nullable<int> NewFirmStatus { get; set; }
        public string OldFirmProduct { get; set; }
        public string NewFirmProduct { get; set; }
        public Nullable<int> ChangeType { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> Approveddate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> CicCharge { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string RComment { get; set; }
        public Nullable<System.DateTime> RCommentDate { get; set; }
    
        public virtual Common_Config Common_Config { get; set; }
        public virtual Common_Config Common_Config1 { get; set; }
        public virtual Customer_ServiceRequest Customer_ServiceRequest { get; set; }
    }
}
