//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class online_Director_Master
    {
        public int Director_Id { get; set; }
        public Nullable<int> onlineapplicationId { get; set; }
        public string Director_Name { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> Director_Share { get; set; }
        public string pan_no { get; set; }
        public Nullable<int> Is_Active { get; set; }
        public Nullable<int> Created_By { get; set; }
    }
}
