//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentScheduleTran
    {
        public PaymentScheduleTran()
        {
            this.PaymentReceiptMsts = new HashSet<PaymentReceiptMst>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public Nullable<int> Rid { get; set; }
        public Nullable<int> InstallmentNo { get; set; }
        public Nullable<decimal> InstallmentAmount { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
        public Nullable<decimal> PenalInterest { get; set; }
        public Nullable<System.DateTime> InstallmentStartDate { get; set; }
        public Nullable<System.DateTime> InstallmentEndDate { get; set; }
        public Nullable<System.DateTime> InstallmentDueDate { get; set; }
        public string InstallmentPeriod { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public string ScheduleType { get; set; }
        public Nullable<bool> IsInstallmentPaid { get; set; }
        public Nullable<bool> IsOneTimeInstallment { get; set; }
        public Nullable<decimal> DuesAmount { get; set; }
        public Nullable<System.DateTime> DuesUptoDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ReceiptHeadId { get; set; }
        public Nullable<int> ReceiptSubHeadId { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public string PaymentMode { get; set; }
        public string TransactionId { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public Nullable<decimal> CurrentDues { get; set; }
        public string HtmlDuesTemplate { get; set; }
        public Nullable<long> PaymentRefId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual PaymentScheduleMaster PaymentScheduleMaster { get; set; }
        public virtual ICollection<PaymentReceiptMst> PaymentReceiptMsts { get; set; }
    }
}
