//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetailTran
    {
        public int Id { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> PaymentSubTypeId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string TransactionId { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> DuesAmount { get; set; }
        public Nullable<System.DateTime> DuesUptoDate { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual PaymentDetailMaster PaymentDetailMaster { get; set; }
    }
}
