//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReceiptMst
    {
        public PaymentReceiptMst()
        {
            this.PaymentReceiptTrans = new HashSet<PaymentReceiptTran>();
        }
    
        public long Id { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public string PlotNo { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public Nullable<int> InstallmentNo { get; set; }
        public Nullable<int> InstallmentRefId { get; set; }
        public Nullable<long> ChallanId { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public string GSTNo { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual PaymentScheduleTran PaymentScheduleTran { get; set; }
        public virtual ICollection<PaymentReceiptTran> PaymentReceiptTrans { get; set; }
    }
}
