//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDuesCalculatedMst
    {
        public int Id { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public string PropertyNo { get; set; }
        public Nullable<decimal> LeaseRentPerYear { get; set; }
        public Nullable<System.DateTime> LeaseRentDueDate { get; set; }
        public Nullable<decimal> LeaseRentDuesAmount { get; set; }
        public Nullable<decimal> LeaseRentInterestAmount { get; set; }
        public Nullable<System.DateTime> LeaseRentDuesUptoDate { get; set; }
        public Nullable<decimal> LeaseRentBalance { get; set; }
        public Nullable<decimal> TotalLeaseRentDues { get; set; }
        public Nullable<int> DaysForLeaseRent { get; set; }
        public string ActionType { get; set; }
        public Nullable<decimal> Installment { get; set; }
        public Nullable<System.DateTime> InstallmentDueDate { get; set; }
        public Nullable<decimal> InstallmentDuesAmount { get; set; }
        public Nullable<decimal> InstallmentInterestAmount { get; set; }
        public Nullable<System.DateTime> InstallmentDuesUptoDate { get; set; }
        public Nullable<decimal> InstallmentBalance { get; set; }
        public Nullable<decimal> TotalInstallmentDues { get; set; }
        public Nullable<decimal> TotalDuesAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
