//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentScheduleMaster
    {
        public PaymentScheduleMaster()
        {
            this.PaymentScheduleTrans = new HashSet<PaymentScheduleTran>();
        }
    
        public int ScheduleId { get; set; }
        public Nullable<int> Rid { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public Nullable<decimal> PrincipalAmount { get; set; }
        public Nullable<int> NoOfInstallment { get; set; }
        public Nullable<int> FrequencyOfInstallment { get; set; }
        public Nullable<int> PeriodOfInstallment { get; set; }
        public Nullable<System.DateTime> InstallmentStartDate { get; set; }
        public Nullable<decimal> NormalInterest { get; set; }
        public Nullable<decimal> PenalInterest { get; set; }
        public string ScheduleType { get; set; }
        public Nullable<bool> IsOneTimeInstallmentPaid { get; set; }
        public Nullable<bool> IsOneTimeLeaseRentPaid { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<PaymentScheduleTran> PaymentScheduleTrans { get; set; }
    }
}
