//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_FULL_PAYMENT_NDC
    {
        public int Id { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public string Applicant { get; set; }
        public string PropertyNo { get; set; }
        public string TotalPaidPream { get; set; }
        public Nullable<double> DuePrincipalAmount { get; set; }
        public Nullable<double> DueIntrestAmount { get; set; }
        public Nullable<System.DateTime> DateUptoPream { get; set; }
        public string OneTimeLease { get; set; }
        public string LeaseRentUpto { get; set; }
        public Nullable<double> LeaseRentAmount { get; set; }
        public Nullable<System.DateTime> NDCDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
