//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_PROP_HIRE_PURCHASE
    {
        public string PRDVREGISTRATION_ID { get; set; }
        public string PRDVAGREEMENT_ID { get; set; }
        public string PRDVEMPLOYEE_ID { get; set; }
        public System.DateTime PRDDENTRY_DATE { get; set; }
        public Nullable<System.DateTime> PRDDHIRE_AGREEMENT_DATE { get; set; }
        public Nullable<decimal> PRDRPROPERTY_COST { get; set; }
        public string PRDVAPPROVAL_ID { get; set; }
        public Nullable<System.DateTime> PRDDEXPIRY_DATE { get; set; }
        public Nullable<System.DateTime> PRDDOLD_EXPIRY_DATE { get; set; }
        public string PRDVORDER_NO { get; set; }
        public Nullable<System.DateTime> PRDDRENEWAL_DATE { get; set; }
        public Nullable<decimal> PRDRPENALTY_AMOUNT { get; set; }
    }
}
