//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_Master
    {
        public Process_Master()
        {
            this.Auto_Schedule = new HashSet<Auto_Schedule>();
            this.Auto_Schedule1 = new HashSet<Auto_Schedule>();
        }
    
        public int Process_Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public string Process_Name { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual ICollection<Auto_Schedule> Auto_Schedule { get; set; }
        public virtual ICollection<Auto_Schedule> Auto_Schedule1 { get; set; }
    }
}
