//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Master
    {
        public int id { get; set; }
        public Nullable<int> Rid { get; set; }
        public string Old_Product_Name { get; set; }
        public string New_Product_Name { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public Nullable<System.DateTime> Approved_Date { get; set; }
        public Nullable<int> Approved_By { get; set; }
        public Nullable<int> Application_Id { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public string Comment { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> Is_Active { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<int> Modified_Date { get; set; }
        public Nullable<int> OnlineRequestNo { get; set; }
    }
}
