//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Cancellation_Details
    {
        public int Id { get; set; }
        public Nullable<int> Rid { get; set; }
        public Nullable<int> Type { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Refund { get; set; }
        public Nullable<int> Refund_Id { get; set; }
        public Nullable<decimal> Refund_Amount { get; set; }
        public Nullable<decimal> Restoration_Charge { get; set; }
        public Nullable<int> Status { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public Nullable<System.DateTime> Approve_Date { get; set; }
        public Nullable<int> Requested_By { get; set; }
        public Nullable<int> Assigned_To { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string RComment { get; set; }
        public Nullable<System.DateTime> RCommentDate { get; set; }
    
        public virtual SchemeRefundTran SchemeRefundTran { get; set; }
    }
}
