//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Ledger
    {
        public int Id { get; set; }
        public Nullable<int> Rid { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public Nullable<int> Receipt_Head_Id { get; set; }
        public Nullable<int> Receipt_Subhead_Id { get; set; }
        public Nullable<decimal> Debit_Amount { get; set; }
        public Nullable<decimal> Credit_Amount { get; set; }
        public Nullable<decimal> Balance_Amount { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Challan_Id { get; set; }
    
        public virtual RECIEPT_HEAD RECIEPT_HEAD { get; set; }
        public virtual RECEIPT_SUB_HEAD RECEIPT_SUB_HEAD { get; set; }
    }
}
