//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotaMst
    {
        public QuotaMst()
        {
            this.ApplicationDetails = new HashSet<ApplicationDetail>();
            this.SchemeQuotaTrans = new HashSet<SchemeQuotaTran>();
        }
    
        public int quotaId { get; set; }
        public string quotaName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual ICollection<ApplicationDetail> ApplicationDetails { get; set; }
        public virtual ICollection<SchemeQuotaTran> SchemeQuotaTrans { get; set; }
    }
}
