//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPTBEFORE2009
    {
        public decimal SLNO { get; set; }
        public string V_NO { get; set; }
        public string V_TYPE { get; set; }
        public string WCODE { get; set; }
        public string MULT { get; set; }
        public Nullable<System.DateTime> V_DAT { get; set; }
        public string V_NO2 { get; set; }
        public string ACODE { get; set; }
        public string CODE { get; set; }
        public string ACNAME { get; set; }
        public string ACODE2 { get; set; }
        public string CODE2 { get; set; }
        public string ACNAME2 { get; set; }
        public string CHALANNO { get; set; }
        public string FAVOR { get; set; }
        public string REF1 { get; set; }
        public string REF2 { get; set; }
        public string DC { get; set; }
        public Nullable<decimal> AMT { get; set; }
        public Nullable<decimal> DRAMT { get; set; }
        public Nullable<decimal> CRAMT { get; set; }
        public string CQCODE { get; set; }
        public string CQNAME { get; set; }
        public string NAR { get; set; }
        public string PROPTRAN { get; set; }
        public string ALLOTNO { get; set; }
        public string TRNTYPE { get; set; }
        public Nullable<decimal> REGNO { get; set; }
        public string YOJCODE { get; set; }
        public string UNAME { get; set; }
        public string DIVCODE { get; set; }
        public string RID_NO { get; set; }
        public Nullable<decimal> RECEIPT_HEAD_ID { get; set; }
        public Nullable<decimal> RECEIPT_SUBHEAD_ID { get; set; }
        public string Sector { get; set; }
        public string Block { get; set; }
        public string PlotNo { get; set; }
    }
}
