//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistryDetail
    {
        public int RequestNo { get; set; }
        public Nullable<int> Rid { get; set; }
        public Nullable<System.DateTime> RegistryDueDate { get; set; }
        public Nullable<System.DateTime> RegistryDoneDate { get; set; }
        public string RegistryType { get; set; }
        public Nullable<decimal> StampDutyAmount { get; set; }
        public Nullable<decimal> DuplicateStampDutyAmount { get; set; }
        public Nullable<decimal> PreviousDues { get; set; }
        public Nullable<decimal> BalanceDueTillDate { get; set; }
        public Nullable<decimal> PenaltyAmount { get; set; }
        public Nullable<decimal> DocumentCharges { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SignatoryAuthority { get; set; }
        public string WitnessOneName { get; set; }
        public string WitnessOneAdd { get; set; }
        public string WitnessOneMobile { get; set; }
        public string WitnessTwoName { get; set; }
        public string WitnessTwoAdd { get; set; }
        public string WitnessTwoMobile { get; set; }
        public string WitnessThreeName { get; set; }
        public string WitnessThreeAdd { get; set; }
        public string WitnessThreeMobile { get; set; }
        public string WitnessFourName { get; set; }
        public string WitnessFourAdd { get; set; }
        public string WitnessFourMobile { get; set; }
        public Nullable<int> LeaseType { get; set; }
    
        public virtual AllotmentMaster AllotmentMaster { get; set; }
    }
}
