//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemeTypeMst
    {
        public SchemeTypeMst()
        {
            this.SchemeMsts = new HashSet<SchemeMst>();
        }
    
        public int schemeTypeId { get; set; }
        public string SchemeTypeDesc { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string SchemeType { get; set; }
    
        public virtual ICollection<SchemeMst> SchemeMsts { get; set; }
    }
}
