//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UmRoleMaster
    {
        public UmRoleMaster()
        {
            this.UmRoleAppTrans = new HashSet<UmRoleAppTran>();
            this.UmRoleMasterTrans = new HashSet<UmRoleMasterTran>();
            this.UmUserMasterRoles = new HashSet<UmUserMasterRole>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string RoleType { get; set; }
        public string RoleInDepartment { get; set; }
        public string RoleDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<UmRoleAppTran> UmRoleAppTrans { get; set; }
        public virtual ICollection<UmRoleMasterTran> UmRoleMasterTrans { get; set; }
        public virtual ICollection<UmUserMasterRole> UmUserMasterRoles { get; set; }
    }
}
