//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UmUserMaster
    {
        public UmUserMaster()
        {
            this.UmUserDepartmentTrans = new HashSet<UmUserDepartmentTran>();
            this.UmUserMasterRoles = new HashSet<UmUserMasterRole>();
        }
    
        public int UserRefId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public string Comments { get; set; }
        public string UserProfile { get; set; }
        public Nullable<int> UserProfileId { get; set; }
        public Nullable<int> OptionalId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> OTP { get; set; }
        public Nullable<System.DateTime> OTPDate { get; set; }
        public Nullable<int> OTP1 { get; set; }
        public Nullable<System.DateTime> OTPDate1 { get; set; }
    
        public virtual ICollection<UmUserDepartmentTran> UmUserDepartmentTrans { get; set; }
        public virtual ICollection<UmUserMasterRole> UmUserMasterRoles { get; set; }
    }
}
