//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string Pasword { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<System.DateTime> LastPasswordChangeDate { get; set; }
        public string PropertyId { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string CustomerIdFileName { get; set; }
        public string CustomerIdFileType { get; set; }
        public string CustomerLetterFileName { get; set; }
        public string CustomerLetterType { get; set; }
        public Nullable<int> OTP { get; set; }
        public string Sector { get; set; }
        public string Block { get; set; }
        public string Property { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsFirstTimeActivated { get; set; }
        public string UserEmail { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
    }
}
