//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VecantPropertyList
    {
        public Nullable<int> Departmentid { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> sectorid { get; set; }
        public string SectorName { get; set; }
        public Nullable<int> blockid { get; set; }
        public string BlockName { get; set; }
        public string propertyno { get; set; }
        public Nullable<decimal> totalarea { get; set; }
        public string LeasHolde { get; set; }
    }
}
