//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRoleWiseApplication
    {
        public int UserRefId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string RoleType { get; set; }
    }
}
