//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_approval_pending_request
    {
        public int Request_No { get; set; }
        public Nullable<int> rid { get; set; }
        public Nullable<int> departmentid { get; set; }
        public string departmentName { get; set; }
        public string Sector { get; set; }
        public string Block { get; set; }
        public string propertyNo { get; set; }
        public Nullable<int> Requested_By { get; set; }
        public string requestedname { get; set; }
        public Nullable<System.DateTime> Requested_Date { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Approved_By { get; set; }
        public string ApprovedName { get; set; }
        public Nullable<System.DateTime> Approved_Date { get; set; }
        public string PagePath { get; set; }
        public string requestType { get; set; }
    }
}
