//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLeaseRentCheck
    {
        public long RECEIPT_ID { get; set; }
        public string RID_NO { get; set; }
        public Nullable<int> RECEIPT_HEAD_ID { get; set; }
        public Nullable<int> RECEIPT_SUBHEAD_ID { get; set; }
        public string Account { get; set; }
        public string Sub_Account { get; set; }
        public string PROPERTY_NUMBER { get; set; }
        public string PROP_ID { get; set; }
        public string ALLOTE_NAME { get; set; }
        public Nullable<int> DEPT_CODE { get; set; }
        public string CHALLAN_ID { get; set; }
        public Nullable<decimal> AMOUNT_PAID { get; set; }
        public Nullable<System.DateTime> DEPOSIT_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<System.DateTime> P_FROM_DATE { get; set; }
        public Nullable<System.DateTime> P_TO_DATE { get; set; }
        public string CONS_NO { get; set; }
    }
}
