//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Service_report
    {
        public int requestNo { get; set; }
        public string Registration_No { get; set; }
        public string PRDVREGIST_APPLICANT_NAME { get; set; }
        public string SECTOR { get; set; }
        public string BLOCK { get; set; }
        public string PLDIPROPERTY_NO { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string ServiceName { get; set; }
        public string RequestorName { get; set; }
        public string RequestorAddress { get; set; }
        public string SubDepartment { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Request_Status { get; set; }
        public string RequestName { get; set; }
        public Nullable<decimal> ServiceFee { get; set; }
        public Nullable<decimal> DuesAmount { get; set; }
        public Nullable<System.DateTime> LastDateofPayment { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<int> ChallanId { get; set; }
        public string PRDVREGIST_APPLICANT_ADDRESS { get; set; }
        public string UploadedDocumentName { get; set; }
        public string DispatchNumber { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<int> DispatchDocumentId { get; set; }
        public string DispatchDocumentName { get; set; }
        public string ServiceType { get; set; }
    }
}
