//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllotmentMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AllotmentMaster()
        {
            this.RentPermissionDetails = new HashSet<RentPermissionDetail>();
        }
    
        public int rid { get; set; }
        public Nullable<int> applicationId { get; set; }
        public Nullable<int> schemeId { get; set; }
        public Nullable<int> departmentId { get; set; }
        public string formNo { get; set; }
        public int propertyId { get; set; }
        public Nullable<System.DateTime> allotmentDate { get; set; }
        public Nullable<System.DateTime> instalmentStartDate { get; set; }
        public string isSubmitted { get; set; }
        public string isStatus { get; set; }
        public Nullable<System.DateTime> submitDate { get; set; }
        public string approverBy { get; set; }
        public Nullable<System.DateTime> approveDate { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<bool> isDocAvailable { get; set; }
        public string comment { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<int> submittedBy { get; set; }
        public string RComment { get; set; }
        public Nullable<System.DateTime> RCommentDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentPermissionDetail> RentPermissionDetails { get; set; }
    }
}
