//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSupportMst
    {
        public int Id { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string SupportType { get; set; }
        public string Issue { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string Path { get; set; }
        public string Username { get; set; }
        public Nullable<int> StatusId { get; set; }
        public int Requestor { get; set; }
        public string RequestDate { get; set; }
        public string RequestorFeedback { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public Nullable<int> Resolver { get; set; }
        public string ResolverFeedback { get; set; }
        public bool IsActive { get; set; }
    }
}
