//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BranchMst()
        {
            this.ApplicationPaymentDetails = new HashSet<ApplicationPaymentDetail>();
            this.SchemeBankTrans = new HashSet<SchemeBankTran>();
        }
    
        public Nullable<int> bankId { get; set; }
        public int branchId { get; set; }
        public string branchName { get; set; }
        public string accountNumber { get; set; }
        public string IFSCcode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string bankBranchCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationPaymentDetail> ApplicationPaymentDetails { get; set; }
        public virtual BankMst BankMst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchemeBankTran> SchemeBankTrans { get; set; }
    }
}
