//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandNoteDetail
    {
        public int Id { get; set; }
        public string NotificationId { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<decimal> InstallmentDues { get; set; }
        public Nullable<decimal> InstallmentDuesInterest { get; set; }
        public Nullable<decimal> LeaseRentDues { get; set; }
        public Nullable<decimal> LeaseRentDuesInterest { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public Nullable<decimal> TotalDuesAmount { get; set; }
        public string DemandNoteTemplate { get; set; }
        public Nullable<int> DemandNoteTypeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDispatched { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<int> ServiceRequestId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Comment { get; set; }
    }
}
