//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionalDetail
    {
        public int RequestNo { get; set; }
        public Nullable<int> Rid { get; set; }
        public string PropertyNumber { get; set; }
        public Nullable<bool> Functional { get; set; }
        public Nullable<System.DateTime> FunctionalDueDate { get; set; }
        public Nullable<System.DateTime> FunctionalDate { get; set; }
        public Nullable<decimal> FunctionalCharge { get; set; }
        public Nullable<bool> MeterSeallingDocFlag { get; set; }
        public Nullable<bool> AffidavitFlag { get; set; }
        public Nullable<bool> RegistrationCertiFlag { get; set; }
        public Nullable<bool> NOCAccountFlag { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> Approver { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string RComment { get; set; }
        public Nullable<System.DateTime> RCommentDate { get; set; }
        public Nullable<int> OnlineRequestNo { get; set; }
        public Nullable<System.DateTime> AffidavitDate { get; set; }
        public Nullable<System.DateTime> ComplitionDate { get; set; }
    
        public virtual StatusMaster StatusMaster { get; set; }
    }
}
