//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEAD_SUB_MASTER
    {
        public int SUB_HEAD_CODE { get; set; }
        public string SUB_HEAD_NAME { get; set; }
        public Nullable<int> HEAD_CODE { get; set; }
        public Nullable<decimal> BUDGET_AMOUNT { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
    
        public virtual HEAD_MASTER HEAD_MASTER { get; set; }
    }
}
