//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYADetail
    {
        public int Id { get; set; }
        public string KYAuid { get; set; }
        public Nullable<int> RId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string AllotteeName { get; set; }
        public string FatherOrHusbandName { get; set; }
        public string AuthorizedSignatory { get; set; }
        public string AllotteeType { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public string PlotNo { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string SignatoryMobileNo { get; set; }
        public string CountryCode { get; set; }
        public string Email { get; set; }
        public string SignatoryEmail { get; set; }
        public string GSTNo { get; set; }
        public string PAN { get; set; }
        public string AadharNo { get; set; }
        public string ROC { get; set; }
        public string CorrespondAddress { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AreaLocality { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public string IdFileType { get; set; }
        public string PlotOwnershipFileType { get; set; }
        public string OtherFileType { get; set; }
        public Nullable<int> ActionId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<System.DateTime> ValidationDate { get; set; }
        public Nullable<int> ValidatorId { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public string Remarks { get; set; }
        public string OptionalAction { get; set; }
        public string KYAReferenceCode { get; set; }
        public Nullable<int> TransferId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
