//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NICsingalwindowSystem
    {
        public int onlineapplicationId { get; set; }
        public Nullable<int> schemeId { get; set; }
        public Nullable<int> Departmentid { get; set; }
        public string Control_ID { get; set; }
        public string Unit_Id { get; set; }
        public string ServiceID { get; set; }
        public string ProcessIndustryID { get; set; }
        public string Company_Name { get; set; }
        public string Industry_District { get; set; }
        public string Industry_District_Id { get; set; }
        public string Industry_Address { get; set; }
        public string Pin_Code { get; set; }
        public string Occupier_Name { get; set; }
        public string Occupier_Email_ID { get; set; }
        public string Occupier_Mobile_No { get; set; }
        public string Occupier_DOB { get; set; }
        public string Occupier_Gender { get; set; }
        public string Occupier_Address { get; set; }
        public string Occupier_District_ID { get; set; }
        public string Occupier_District_Name { get; set; }
        public string Occupier_Pin_Code { get; set; }
        public string Nature_of_Activity { get; set; }
        public string Installed_Capacity { get; set; }
        public string Employees { get; set; }
        public string Nature_of_Operation { get; set; }
        public string publicdecimalProject_Cost { get; set; }
        public string Organization_Type_ID { get; set; }
        public string Organization_Type { get; set; }
        public string Industry_Type_ID { get; set; }
        public string Industry_Type_Name { get; set; }
        public string Expected_date_construction { get; set; }
        public string Project_Status { get; set; }
        public string Industry_Color { get; set; }
        public string Expected_date_production { get; set; }
        public string Unit_Category { get; set; }
        public string Items_Manufactured { get; set; }
        public string Annual_Turnover { get; set; }
        public Nullable<decimal> Fee_Amount { get; set; }
        public string Fee_Status { get; set; }
        public Nullable<int> Status_Code { get; set; }
        public Nullable<int> Payment_Through { get; set; }
        public string Payment_Description { get; set; }
        public string NICRequestId { get; set; }
        public string ReasonRefId { get; set; }
        public string Remarks { get; set; }
    }
}
