//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NiveshMitraEntr_Master
    {
        public int ID { get; set; }
        public string ControlID { get; set; }
        public string UnitID { get; set; }
        public string ServiceID { get; set; }
        public string ProcessIndustryID { get; set; }
        public string ApplicationID { get; set; }
        public string Sector { get; set; }
        public string Block { get; set; }
        public string PlotNo { get; set; }
        public string MobileNo { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string NICRequestID { get; set; }
        public string ReasonRefId { get; set; }
        public string Remarks { get; set; }
    }
}
