//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlinePropertyCancellationDetail
    {
        public int CSRSid { get; set; }
        public int RequestNo { get; set; }
        public Nullable<int> Rid { get; set; }
        public Nullable<int> Type { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Refund { get; set; }
        public Nullable<int> RefundId { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public Nullable<decimal> RestorationCharge { get; set; }
        public Nullable<int> Status { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<int> RequestedBy { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string RComment { get; set; }
        public Nullable<System.DateTime> RCommentDate { get; set; }
    
        public virtual SchemeRefundTran SchemeRefundTran { get; set; }
        public virtual Customer_ServiceRequest Customer_ServiceRequest { get; set; }
    }
}
