//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PossessionDetail
    {
        public int Id { get; set; }
        public Nullable<int> Rid { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public Nullable<System.DateTime> PossessionOrderDate { get; set; }
        public Nullable<System.DateTime> PossessionDueDate { get; set; }
        public Nullable<System.DateTime> PossessionDate { get; set; }
        public string AreaChange { get; set; }
        public string AreaChangeType { get; set; }
        public Nullable<decimal> OneTimeExcessCharge { get; set; }
        public Nullable<decimal> ChnagedArea { get; set; }
        public Nullable<bool> Possession { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> PenaltyAmount { get; set; }
        public string North { get; set; }
        public string East { get; set; }
        public string West { get; set; }
        public string South { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string PossessionBy { get; set; }
        public Nullable<int> Approver { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> OnlineRequestNo { get; set; }
    
        public virtual StatusMaster StatusMaster { get; set; }
    }
}
