//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemeBankTran
    {
        public Nullable<int> schemeId { get; set; }
        public int refId { get; set; }
        public Nullable<int> bankId { get; set; }
        public Nullable<int> branchId { get; set; }
        public string accountnumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string IFSCCode { get; set; }
        public string virtualAccountprefix { get; set; }
    
        public virtual BankMst BankMst { get; set; }
        public virtual BranchMst BranchMst { get; set; }
        public virtual SchemeMst SchemeMst { get; set; }
    }
}
