//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemeAreaMst
    {
        public int Id { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> SchemeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string AreaRange { get; set; }
        public Nullable<decimal> ApproxArea { get; set; }
        public Nullable<int> PropertyTypeRefId { get; set; }
        public string AreaForUse { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> SectorRate { get; set; }
        public Nullable<decimal> ReservedPrice { get; set; }
        public Nullable<decimal> ProcessingFee { get; set; }
        public Nullable<decimal> EarnestMoney { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
