//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemeRefundTran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SchemeRefundTran()
        {
            this.OnlinePropertyCancellationDetails = new HashSet<OnlinePropertyCancellationDetail>();
        }
    
        public int refundId { get; set; }
        public Nullable<int> schemeId { get; set; }
        public Nullable<int> departmentId { get; set; }
        public string refundDescription { get; set; }
        public Nullable<int> refundLockPeriod { get; set; }
        public Nullable<int> mediaTypeId { get; set; }
        public Nullable<decimal> deduction { get; set; }
        public string unit { get; set; }
        public string deductionApplyOn { get; set; }
        public Nullable<int> interest { get; set; }
        public Nullable<int> daysAfterInterest { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlinePropertyCancellationDetail> OnlinePropertyCancellationDetails { get; set; }
        public virtual SchemeMst SchemeMst { get; set; }
    }
}
