//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemePropTran
    {
        public int refId { get; set; }
        public Nullable<int> schemeId { get; set; }
        public Nullable<int> departmentId { get; set; }
        public Nullable<int> propertyTypeId { get; set; }
        public Nullable<int> sectorId { get; set; }
        public Nullable<int> blockId { get; set; }
        public Nullable<int> floorId { get; set; }
        public Nullable<int> propertyId { get; set; }
        public string propertyNo { get; set; }
        public Nullable<decimal> landRatePerSqmt { get; set; }
        public Nullable<decimal> TotalAllotmentRate { get; set; }
        public Nullable<decimal> AllottedArea { get; set; }
        public Nullable<decimal> totalArea { get; set; }
        public Nullable<decimal> coveredArea { get; set; }
        public Nullable<decimal> actualArea { get; set; }
        public Nullable<decimal> propertyCost { get; set; }
        public Nullable<decimal> civilCost { get; set; }
        public Nullable<decimal> totalPropertyCost { get; set; }
        public string Registry { get; set; }
        public Nullable<decimal> Processingfee { get; set; }
        public Nullable<decimal> EarnestMoney { get; set; }
        public Nullable<decimal> allotmentMoney { get; set; }
        public Nullable<decimal> LeaseRent { get; set; }
        public Nullable<decimal> AdvanceLeaseRent { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> ExcessAreaRefId { get; set; }
        public Nullable<bool> IsExcessArea { get; set; }
        public Nullable<int> VillageId { get; set; }
        public string KhasraNumber { get; set; }
        public string KhatoniNumber { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> ParentPropertyId { get; set; }
        public Nullable<int> groupProjectId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual BlockMst BlockMst { get; set; }
        public virtual DepartmentMst DepartmentMst { get; set; }
        public virtual FloorMst FloorMst { get; set; }
        public virtual SchemeMst SchemeMst { get; set; }
        public virtual SectorMst SectorMst { get; set; }
    }
}
