//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCheckList_Master
    {
        public int ChkId { get; set; }
        public Nullable<int> dept_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> Checklist_Ref { get; set; }
        public string ChkName { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
