//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.OnlineScheme.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateMaster
    {
        public int id { get; set; }
        public Nullable<int> templateId { get; set; }
        public Nullable<int> departmentId { get; set; }
        public string templateName { get; set; }
        public Nullable<System.DateTime> efficatedTo { get; set; }
        public Nullable<System.DateTime> efficatedFrom { get; set; }
        public string templateKeyValue { get; set; }
        public string templateHtml { get; set; }
        public string sqlQuery { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string CopyTo { get; set; }
        public string Signature { get; set; }
    
        public virtual DepartmentMst DepartmentMst { get; set; }
    }
}
