//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NA.PMS.Dal.CustomerContext
{
    using NA.PMS.Model.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomerContext : DbContext
    {
        public CustomerContext()
            : base("name=CustomerContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer_Feedback> Customer_Feedback { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Property_Remarks> Property_Remarks { get; set; }
        public virtual DbSet<Role_Menu_Mapping> Role_Menu_Mapping { get; set; }
        public virtual DbSet<Role_Users> Role_Users { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<view_property> view_property { get; set; }
        public virtual DbSet<LookupDepartment> LookupDepartments { get; set; }
    }
}
